<div class="top-brands-container">
<div class="main">
 <h2>Top Brands</h2>
    <div class="top-brands-content">
        <div class="bx-wrapper"><div class="bx-viewport" style="width: 100%; height: 72px; overflow: hidden; position: relative;">
        <ul class="brands-slider clearfix" style="width: 2800%; height: 0px; overflow: visible; position: relative; margin: 0px; padding: 0px; transition-duration: 0s; transform: translate3d(-1632px, 0px, 0px);">
        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;" class="bx-clone"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=HP" title="HP"><span><img  alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=HP" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/hp.png" alt="HP"></span></a></li>

        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;" class="bx-clone"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=HTC" title="HTC"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=HTC" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/htc.png" alt="HTC"></span></a></li>

        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;" class="bx-clone"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=Lenovo" title="Lenovo"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=Lenovo" src="https://electronicsbazaar.com/media/wysiwyg/sell_gadget/mobile/lenovo_brand.png" alt="Lenovo"></span></a></li>

        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;" class="bx-clone"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=Nokia" title="Nokia"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=Nokia" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/nokia.png" alt="Nokia"></span></a></li>

        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;" class="bx-clone"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=Toshiba"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=Toshiba" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/toshiba.png"></span></a></li>

        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;" class="bx-clone"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=Samsung"><span><img alt="samsung" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/samsung.png"></span></a></li> 

        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=Apple"><span><img alt="apple" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/apple.png"></span></a></li> 
                                            
        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=asus"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=asus" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/asus.png"></span></a></li> 
        
        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=BlackBerry"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=BlackBerry" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/blackberry.png"></span></a></li> 
        
        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=Dell"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=Dell" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/dell.png"></span></a></li> 
                                            
                                            
        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=Lenovo"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=Lenovo" src="https://electronicsbazaar.com/media/wysiwyg/sell_gadget/mobile/lenovo_brand.png"></span></a></li> 
                                            
        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=Nokia"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=Nokia" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/nokia.png"></span></a></li> 
        
        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=Toshiba"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=Toshiba" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/toshiba.png"></span></a></li> 
        
        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=Samsung"><span><img alt="samsung" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/samsung.png"></span></a></li> 
                                    
        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;" class="bx-clone"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=Apple"><span><img alt="apple" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/apple.png"></span></a></li>

        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;" class="bx-clone"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=asus"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=asus" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/asus.png"></span></a></li>

        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;" class="bx-clone"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=BlackBerry"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=BlackBerry" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/blackberry.png"></span></a></li>

        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;" class="bx-clone"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=Dell"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=Dell" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/dell.png"></span></a></li>

        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;" class="bx-clone"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=HP"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=HP" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/hp.png"></span></a></li>

        <li style="margin-right: 10px; backface-visibility: hidden; float: left; position: relative; width: 200px; list-style: outside none none; margin-bottom: 0px;" class="bx-clone"><a href="http://www.electronicsbazaar.com/catalogsearch/result/?q=HTC"><span><img alt="http://www.electronicsbazaar.com/catalogsearch/result/?q=HTC" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/htc.png"></span></a></li>
        </ul>
        </div>
        </div> 
    </div>
    </div>
</div>

<script type="text/javascript">
    var jq = jQuery.noConflict();
    jq(document).ready(function(){ 
      jq('.brands-slider').bxSlider({
         slideWidth: 200,
         auto: true,
         speed: 9000, 
         pager: false,
         controls: false,
         pause: 1, 
         maxSlides: 6,
         slideMargin:10, 
         infiniteLoop: true 
      });
    }); 
 


</script>
 