<!-- <div class="deals-heading">
  	<img src="<?php // echo $this->helper('neo_sidebanner')->getDealsHeaderImage() ?>" alt="" />
</div> -->
<?php $product_list_block = new Mage_Catalog_Block_Product_List(); ?>
<div class="deals-category-list">
	<ul class="clearfix">
		<li class="active"><a id="link1" href="#section1">Brand new mobiles</a></li>
		<li><a id="link2" href="#section2">Brand new laptops</a></li>
		<li><a id="link3" href="#section3">Open box mobiles</a></li>
		<li><a id="link4" href="#section4">Pre owned mobiles</a></li>
		<li><a id="link5" href="#section5">Pre owned laptops</a></li>
		<li><a id="link6" href="#section6">Accessories</a></li>
	</ul>
</div>
<div class="deals-container">
    <div class="deals-list-content">        
    	<div class="sale-list-container">        
    	<!-- Brand New mobiles-->
        <div id="section1" class="recently-viewed-container1 category-products_test products_homeslider products-grid">
        	<div>
        		<h2 class="home-slider-heading"><?php echo $this->__('Brand New Mobiles') ?></h2>
        		<ul class="products-grid recently-viewed1">
	            	<?php $sealPackCollection = $this->helper('neo_sidebanner')->getNewMobile() ?>
	            	<?php foreach($sealPackCollection as $openproids): ?>
	            		<?php 
            			$_item = Mage::getModel('catalog/product')->load($openproids); 							
						if($_item->isSaleable()):
		         		?> 
		                <li class="item">
            				<div class="item-wrapper">
            					<?php $hasProduct = 0; ?>
								<?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>
									<?php $customerId = Mage::getSingleton('customer/session')->getCustomerId(); ?>
									<?php $wishlist = Mage::getModel('wishlist/wishlist')->loadByCustomer($customerId, true); ?>
									<?php $collection = Mage::getModel('wishlist/item')->getCollection()->addFieldToFilter('wishlist_id', $wishlist->getId())->addFieldToFilter('product_id', $_item->getId()); ?>
									<?php $item = $collection->getFirstItem(); ?>
									<?php $hasProduct = $item->getWishlistItemId(); ?>
			                    <?php endif; ?>
			                    <ul class="add-to-links">
			                        <?php if($hasProduct): ?>
			                            <li><a href="<?php echo $this->getBaseUrl() ?>wishlist/index/remove/item/<?php echo $hasProduct?>" class="link-wishlist added-to-wishlist"><?php echo $this->__('Remove from Wishlist') ?></a>
			                            </li>
			                        <?php else: ?>
			                            <li><a class="link-wishlist" title="Add to Wishlist" onclick="setLocation('<?php echo $product_list_block->getAddToWishlistUrl($_item); ?>')">Add to Wishlist</a>
			                            </li>
			                        <?php endif; ?>
			                    </ul>
            					<div class="product-image-container">
									<a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $_item->getName() ?>" class="product-image">
										<?php $_imgSize = 210; ?>
										<span><img id="product-collection-image-<?php echo $_item->getId(); ?>" src="<?php echo Mage::helper('catalog/image')->init($_item,'small_image')->resize($_imgSize); ?>" alt="<?php echo $_item->getName(); ?>"  /></span>
										<div class="mask"></div>
									</a>
								</div>
								<div class="product-info">
									<h2 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $_item->getName(); ?>"><?php echo substr($_item->getName(),0,28); ?><?php if(strlen($_item->getName()) > 28) { echo '...'; } ?></a></h2>                                        
				 					 <?php // if(Mage::helper('customer')->isLoggedin()): ?>
				 					 	<?php echo $this->getLayout()->getBlockSingleton('catalog/product_list')->getPriceHtml($_item, true) ?>
				 					 	<!-- </div> -->
                                    <?php /* else: ?>
										</div>
                                        <div class="product-info-custom">
                                            <a class="view-price" href="<?php echo $this->getUrl('customer/account/login');?>">Login to view Price</a>
                                        </div>
                                    <?php endif; */ ?>
                                    </div>				
								<div class="short-description">
									<div class="c-prod-desc"><?php echo $_item->getImpDesc(); ?></div>
								</div>
								<div class="actions">
									<button class="button btn-cart" title="Add To Cart" type="button" onclick="setLocation('<?php echo $this->getLayout()->getBlockSingleton('catalog/product_list')->getAddToCartUrl($_item); ?>')"><span><span>Add To Cart</span></span></button>
									<div class="clr"></div>
								</div>
			                
		                </li>
            			<?php endif; ?>
            		<?php endforeach; ?>
            	</ul>
	        </div>
	    </div>

        <div id="section2" class="recently-viewed-container1 category-products_test products_homeslider products-grid">
        	<div>
        		<h2 class="home-slider-heading"><?php echo $this->__('Brand New Laptops') ?></h2>
        		<ul class="products-grid recently-viewed1">
	            	<?php $sealPackCollection = $this->helper('neo_sidebanner')->getNewLaptop() ?>
	            	<?php foreach($sealPackCollection as $openproids): ?>
	            		<?php 
            			$_item = Mage::getModel('catalog/product')->load($openproids); 							
						if($_item->isSaleable()):
		         		?> 
		                <li class="item">
            				<div class="item-wrapper">
            					<?php $hasProduct = 0; ?>
								<?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>
									<?php $customerId = Mage::getSingleton('customer/session')->getCustomerId(); ?>
									<?php $wishlist = Mage::getModel('wishlist/wishlist')->loadByCustomer($customerId, true); ?>
									<?php $collection = Mage::getModel('wishlist/item')->getCollection()->addFieldToFilter('wishlist_id', $wishlist->getId())->addFieldToFilter('product_id', $_item->getId()); ?>
									<?php $item = $collection->getFirstItem(); ?>
									<?php $hasProduct = $item->getWishlistItemId(); ?>
			                    <?php endif; ?>
			                    <ul class="add-to-links">
			                        <?php if($hasProduct): ?>
			                            <li><a href="<?php echo $this->getBaseUrl() ?>wishlist/index/remove/item/<?php echo $hasProduct?>" class="link-wishlist added-to-wishlist"><?php echo $this->__('Remove from Wishlist') ?></a>
			                            </li>
			                        <?php else: ?>
			                            <li><a class="link-wishlist" title="Add to Wishlist" onclick="setLocation('<?php echo $product_list_block->getAddToWishlistUrl($_item); ?>')">Add to Wishlist</a>
			                            </li>
			                        <?php endif; ?>
			                    </ul>
            					<div class="product-image-container">
									<a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $_item->getName() ?>" class="product-image">
										<?php $_imgSize = 210; ?>
										<span><img id="product-collection-image-<?php echo $_item->getId(); ?>" src="<?php echo Mage::helper('catalog/image')->init($_item,'small_image')->resize($_imgSize); ?>" alt="<?php echo $_item->getName(); ?>"  /></span>
										<div class="mask"></div>
									</a>
								</div>
								<div class="product-info">
									<h2 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $_item->getName(); ?>"><?php echo substr($_item->getName(),0,28); ?><?php if(strlen($_item->getName()) > 28) { echo '...'; } ?></a></h2>
									 <?php // if(Mage::helper('customer')->isLoggedin()): ?>
				 					 	<?php echo $this->getLayout()->getBlockSingleton('catalog/product_list')->getPriceHtml($_item, true) ?>
				 					 	<!-- </div> -->
                                    <?php /* else: ?>
										</div>
                                        <div class="product-info-custom">
                                            <a class="view-price" href="<?php echo $this->getUrl('customer/account/login');?>">Login to view Price</a>
                                        </div>
                                    <?php endif; */ ?>
                                    </div>									
								<div class="short-description">
									<div class="c-prod-desc"><?php echo $_item->getImpDesc(); ?></div>
								</div>
								<div class="actions">
									<button class="button btn-cart" title="Add To Cart" type="button" onclick="setLocation('<?php echo $this->getLayout()->getBlockSingleton('catalog/product_list')->getAddToCartUrl($_item); ?>')"><span><span>Add To Cart</span></span></button>
									<div class="clr"></div>
								</div>
			                </div>
		                </li>
            			<?php endif; ?>
            		<?php endforeach; ?>
            	</ul>
	        </div>
	    </div>
	    <div id="section3" class="recently-viewed-container1 category-products_test products_homeslider products-grid">
        	<div>
        		<h2 class="home-slider-heading"><?php echo $this->__('Open Box Mobiles') ?></h2>
        		<ul class="products-grid recently-viewed1">
	            	<?php $sealPackCollection = $this->helper('neo_sidebanner')->getOpenMobile() ?>
	            	<?php foreach($sealPackCollection as $openproids): ?>
	            		<?php 
            			$_item = Mage::getModel('catalog/product')->load($openproids); 							
						if($_item->isSaleable()):
		         		?> 
		                <li class="item">
            				<div class="item-wrapper">
            					<?php $hasProduct = 0; ?>
								<?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>
									<?php $customerId = Mage::getSingleton('customer/session')->getCustomerId(); ?>
									<?php $wishlist = Mage::getModel('wishlist/wishlist')->loadByCustomer($customerId, true); ?>
									<?php $collection = Mage::getModel('wishlist/item')->getCollection()->addFieldToFilter('wishlist_id', $wishlist->getId())->addFieldToFilter('product_id', $_item->getId()); ?>
									<?php $item = $collection->getFirstItem(); ?>
									<?php $hasProduct = $item->getWishlistItemId(); ?>
			                    <?php endif; ?>
			                    <ul class="add-to-links">
			                        <?php if($hasProduct): ?>
			                            <li><a href="<?php echo $this->getBaseUrl() ?>wishlist/index/remove/item/<?php echo $hasProduct?>" class="link-wishlist added-to-wishlist"><?php echo $this->__('Remove from Wishlist') ?></a>
			                            </li>
			                        <?php else: ?>
			                            <li><a class="link-wishlist" title="Add to Wishlist" onclick="setLocation('<?php echo $product_list_block->getAddToWishlistUrl($_item); ?>')">Add to Wishlist</a>
			                            </li>
			                        <?php endif; ?>
			                    </ul>
            					<div class="product-image-container">
									<a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $_item->getName() ?>" class="product-image">
										<?php $_imgSize = 210; ?>
										<span><img id="product-collection-image-<?php echo $_item->getId(); ?>" src="<?php echo Mage::helper('catalog/image')->init($_item,'small_image')->resize($_imgSize); ?>" alt="<?php echo $_item->getName(); ?>"  /></span>
										<div class="mask"></div>
									</a>
								</div>
								<div class="product-info">
									<h2 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $_item->getName(); ?>"><?php echo substr($_item->getName(),0,28); ?><?php if(strlen($_item->getName()) > 28) { echo '...'; } ?></a></h2>
									  <?php // if(Mage::helper('customer')->isLoggedin()): ?>
				 					 	<?php echo $this->getLayout()->getBlockSingleton('catalog/product_list')->getPriceHtml($_item, true) ?>
				 					 	<!-- </div> -->
                                    <?php /* else: ?>
										</div>
                                        <div class="product-info-custom">
                                            <a class="view-price" href="<?php echo $this->getUrl('customer/account/login');?>">Login to view Price</a>
                                        </div>
                                    <?php endif; */ ?>
                                    </div>										
								<div class="short-description">
									<div class="c-prod-desc"><?php echo $_item->getImpDesc(); ?></div>
								</div>
								<div class="actions">
									<button class="button btn-cart" title="Add To Cart" type="button" onclick="setLocation('<?php echo $this->getLayout()->getBlockSingleton('catalog/product_list')->getAddToCartUrl($_item); ?>')"><span><span>Add To Cart</span></span></button>
									<div class="clr"></div>
								</div>
			                
		                </li>
            			<?php endif; ?>
            		<?php endforeach; ?>
            	</ul>
	        </div>
	    </div>
	    <div id="section4" class="recently-viewed-container1 category-products_test products_homeslider products-grid">
        	<div>
        		<h2 class="home-slider-heading"><?php echo $this->__('Pre Owned Mobiles') ?></h2>
        		<ul class="products-grid recently-viewed1">
	            	<?php $sealPackCollection = $this->helper('neo_sidebanner')->getPreOwnedMobile() ?>
	            	<?php foreach($sealPackCollection as $openproids): ?>
	            		<?php 
            			$_item = Mage::getModel('catalog/product')->load($openproids); 							
						if($_item->isSaleable()):
		         		?> 
		                <li class="item">
            				<div class="item-wrapper">
            					<?php $hasProduct = 0; ?>
								<?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>
									<?php $customerId = Mage::getSingleton('customer/session')->getCustomerId(); ?>
									<?php $wishlist = Mage::getModel('wishlist/wishlist')->loadByCustomer($customerId, true); ?>
									<?php $collection = Mage::getModel('wishlist/item')->getCollection()->addFieldToFilter('wishlist_id', $wishlist->getId())->addFieldToFilter('product_id', $_item->getId()); ?>
									<?php $item = $collection->getFirstItem(); ?>
									<?php $hasProduct = $item->getWishlistItemId(); ?>
			                    <?php endif; ?>
			                    <ul class="add-to-links">
			                        <?php if($hasProduct): ?>
			                            <li><a href="<?php echo $this->getBaseUrl() ?>wishlist/index/remove/item/<?php echo $hasProduct?>" class="link-wishlist added-to-wishlist"><?php echo $this->__('Remove from Wishlist') ?></a>
			                            </li>
			                        <?php else: ?>
			                            <li><a class="link-wishlist" title="Add to Wishlist" onclick="setLocation('<?php echo $product_list_block->getAddToWishlistUrl($_item); ?>')">Add to Wishlist</a>
			                            </li>
			                        <?php endif; ?>
			                    </ul>
            					<div class="product-image-container">
									<a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $_item->getName() ?>" class="product-image">
										<?php $_imgSize = 210; ?>
										<span><img id="product-collection-image-<?php echo $_item->getId(); ?>" src="<?php echo Mage::helper('catalog/image')->init($_item,'small_image')->resize($_imgSize); ?>" alt="<?php echo $_item->getName(); ?>"  /></span>
										<div class="mask"></div>
									</a>
								</div>
								<div class="product-info">
									<h2 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $_item->getName(); ?>"><?php echo substr($_item->getName(),0,28); ?><?php if(strlen($_item->getName()) > 28) { echo '...'; } ?></a></h2>
									  <?php // if(Mage::helper('customer')->isLoggedin()): ?>
				 					 	<?php echo $this->getLayout()->getBlockSingleton('catalog/product_list')->getPriceHtml($_item, true) ?>
				 					 	<!-- </div> -->
                                    <?php /* else: ?>
										</div>
                                        <div class="product-info-custom">
                                            <a class="view-price" href="<?php echo $this->getUrl('customer/account/login');?>">Login to view Price</a>
                                        </div>
                                    <?php endif; */ ?>	
                                    </div>									
								<div class="short-description">
									<div class="c-prod-desc"><?php echo $_item->getImpDesc(); ?></div>
								</div>
								<div class="actions">
									<button class="button btn-cart" title="Add To Cart" type="button" onclick="setLocation('<?php echo $this->getLayout()->getBlockSingleton('catalog/product_list')->getAddToCartUrl($_item); ?>')"><span><span>Add To Cart</span></span></button>
									<div class="clr"></div>
								</div>
			                </div>
		                </li>
            			<?php endif; ?>
            		<?php endforeach; ?>
            	</ul>
	        </div>
	    </div>
	    <div id="section5" class="recently-viewed-container1 category-products_test products_homeslider products-grid">
        	<div>
        		<h2 class="home-slider-heading"><?php echo $this->__('Pre Owned Laptops') ?></h2>
        		<ul class="products-grid recently-viewed1">
	            	<?php $sealPackCollection = $this->helper('neo_sidebanner')->getPreOwnedLap() ?>
	            	<?php foreach($sealPackCollection as $openproids): ?>
	            		<?php 
            			$_item = Mage::getModel('catalog/product')->load($openproids); 							
						if($_item->isSaleable()):
		         		?> 
		                <li class="item">
            				<div class="item-wrapper">
            					<?php $hasProduct = 0; ?>
								<?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>
									<?php $customerId = Mage::getSingleton('customer/session')->getCustomerId(); ?>
									<?php $wishlist = Mage::getModel('wishlist/wishlist')->loadByCustomer($customerId, true); ?>
									<?php $collection = Mage::getModel('wishlist/item')->getCollection()->addFieldToFilter('wishlist_id', $wishlist->getId())->addFieldToFilter('product_id', $_item->getId()); ?>
									<?php $item = $collection->getFirstItem(); ?>
									<?php $hasProduct = $item->getWishlistItemId(); ?>
			                    <?php endif; ?>
			                    <ul class="add-to-links">
			                        <?php if($hasProduct): ?>
			                            <li><a href="<?php echo $this->getBaseUrl() ?>wishlist/index/remove/item/<?php echo $hasProduct?>" class="link-wishlist added-to-wishlist"><?php echo $this->__('Remove from Wishlist') ?></a>
			                            </li>
			                        <?php else: ?>
			                            <li><a class="link-wishlist" title="Add to Wishlist" onclick="setLocation('<?php echo $product_list_block->getAddToWishlistUrl($_item); ?>')">Add to Wishlist</a>
			                            </li>
			                        <?php endif; ?>
			                    </ul>
            					<div class="product-image-container">
									<a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $_item->getName() ?>" class="product-image">
										<?php $_imgSize = 210; ?>
										<span><img id="product-collection-image-<?php echo $_item->getId(); ?>" src="<?php echo Mage::helper('catalog/image')->init($_item,'small_image')->resize($_imgSize); ?>" alt="<?php echo $_item->getName(); ?>"  /></span>
										<div class="mask"></div>
									</a>
								</div>
								<div class="product-info">
									<h2 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $_item->getName(); ?>"><?php echo substr($_item->getName(),0,28); ?><?php if(strlen($_item->getName()) > 28) { echo '...'; } ?></a></h2>
									  <?php // if(Mage::helper('customer')->isLoggedin()): ?>
				 					 	<?php echo $this->getLayout()->getBlockSingleton('catalog/product_list')->getPriceHtml($_item, true) ?>
				 					 	<!-- </div> -->
                                    <?php /* else: ?>
										</div>
                                        <div class="product-info-custom">
                                            <a class="view-price" href="<?php echo $this->getUrl('customer/account/login');?>">Login to view Price</a>
                                        </div>
                                    <?php endif; */ ?>	
                                    </div>					
								<div class="short-description">
									<div class="c-prod-desc"><?php echo $_item->getImpDesc(); ?></div>
								</div>
								<div class="actions">
									<button class="button btn-cart" title="Add To Cart" type="button" onclick="setLocation('<?php echo $this->getLayout()->getBlockSingleton('catalog/product_list')->getAddToCartUrl($_item); ?>')"><span><span>Add To Cart</span></span></button>
									<div class="clr"></div>
								</div>
			                </div>
		                </li>
            			<?php endif; ?>
            		<?php endforeach; ?>
            	</ul>
	        </div>
	    </div>
	    <div id="section6" class="recently-viewed-container1 category-products_test products_homeslider products-grid">
        	<div>
        		<h2 class="home-slider-heading"><?php echo $this->__('Accessories') ?></h2>
        		<ul class="products-grid recently-viewed1">
	            	<?php $sealPackCollection = $this->helper('neo_sidebanner')->getAccessories() ?>
	            	<?php foreach($sealPackCollection as $openproids): ?>
	            		<?php 
            			$_item = Mage::getModel('catalog/product')->load($openproids); 							
						if($_item->isSaleable()):
		         		?> 
		                <li class="item">
            				<div class="item-wrapper">
            					<?php $hasProduct = 0; ?>
								<?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>
									<?php $customerId = Mage::getSingleton('customer/session')->getCustomerId(); ?>
									<?php $wishlist = Mage::getModel('wishlist/wishlist')->loadByCustomer($customerId, true); ?>
									<?php $collection = Mage::getModel('wishlist/item')->getCollection()->addFieldToFilter('wishlist_id', $wishlist->getId())->addFieldToFilter('product_id', $_item->getId()); ?>
									<?php $item = $collection->getFirstItem(); ?>
									<?php $hasProduct = $item->getWishlistItemId(); ?>
			                    <?php endif; ?>
				                    <ul class="add-to-links">
			                        <?php if($hasProduct): ?>
			                            <li><a href="<?php echo $this->getBaseUrl() ?>wishlist/index/remove/item/<?php echo $hasProduct?>" class="link-wishlist added-to-wishlist"><?php echo $this->__('Remove from Wishlist') ?></a>
			                            </li>
			                        <?php else: ?>
			                            <li><a class="link-wishlist" title="Add to Wishlist" onclick="setLocation('<?php echo $product_list_block->getAddToWishlistUrl($_item); ?>')">Add to Wishlist</a>
			                            </li>
			                        <?php endif; ?>
			                    </ul>
            					<div class="product-image-container">
									<a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $_item->getName() ?>" class="product-image">
										<?php $_imgSize = 210; ?>
										<span><img id="product-collection-image-<?php echo $_item->getId(); ?>" src="<?php echo Mage::helper('catalog/image')->init($_item,'small_image')->resize($_imgSize); ?>" alt="<?php echo $_item->getName(); ?>"  /></span>
										<div class="mask"></div>
									</a>
								</div>
								<div class="product-info">
									<h2 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $_item->getName(); ?>"><?php echo substr($_item->getName(),0,28); ?><?php if(strlen($_item->getName()) > 28) { echo '...'; } ?></a></h2>
									 <?php // if(Mage::helper('customer')->isLoggedin()): ?>
				 					 	<?php echo $this->getLayout()->getBlockSingleton('catalog/product_list')->getPriceHtml($_item, true) ?>
				 					 	<!-- </div> -->
                                    <?php /* else: ?>
                                        <div class="product-info-custom">
                                            <a class="view-price" href="<?php echo $this->getUrl('customer/account/login');?>">Login to view Price</a>
                                        </div>
                                    <?php endif; */ ?>																		
										</div>
								<div class="short-description">
									<div class="c-prod-desc"><?php echo $_item->getImpDesc(); ?></div>
								</div>
								<div class="actions">
									<button class="button btn-cart" title="Add To Cart" type="button" onclick="setLocation('<?php echo $this->getLayout()->getBlockSingleton('catalog/product_list')->getAddToCartUrl($_item); ?>')"><span><span>Add To Cart</span></span></button>
									<div class="clr"></div>
								</div>
			                </div>
		                </li>
            			<?php endif; ?>
            		<?php endforeach; ?>
            	</ul>
	        </div>
	    </div>
	    </div>
    </div> 
</div>
<script type="text/javascript">// <![CDATA[
    var jnsde = jQuery.noConflict();
    jnsde(window).bind("load", function () {
        history.pushState("", document.title, window.location.pathname);
    });
// ]]></script>

<script type="text/javascript">
var dl = jQuery.noConflict();
dl(document).ready(function() {
	dl(window).scroll(function(e) { 
		// console.log(dl('.deals-container').offset().top);   
		e.stopPropagation();
    var scroll = dl(window).scrollTop();
    var spos = dl('.deals-container').offset().top - dl('.top-header').height();
    if (scroll >= spos) {
        dl(".deals-category-list").addClass("active");
        dl(".deals-container").addClass("active");
    } else {
        dl(".deals-category-list").removeClass("active");
        dl(".deals-container").removeClass("active");
    }
	});

 function scrollNav() { 	
  dl('.deals-category-list ul li a').click(function(e){  
  	e.stopPropagation();
  	var spos = dl('.deals-container').offset().top - dl('.top-header').height();
    //Toggle Class
    dl(".active").removeClass("active");      
    dl(this).closest('li').addClass("active");
    var theClass = dl(this).attr("class");
    dl('.'+theClass).parent('li').addClass('active');
    //Animate
    dl('html, body').stop().animate({
        scrollTop: dl( dl(this).attr('href') ).offset().top - spos
    }, 0);
    return false;
  });
}
scrollNav();
});
</script>

