<?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>
	<?php $customer = Mage::getSingleton('customer/session')->getCustomer(); ?>
	<?php $repcode = $customer->getRepcode(); ?>
<?php endif; ?>
<?php if($customer->getIsaffiliate()): ?>
<div class="field repcode-block" id="repcode-block">
	<h3><?php echo $this->__('Rep Code')?></h3>
	<form autocomplete="off">
		<ul class="checkout-agreements">
			<li class="fields">
				<div class="field">
					<label for="neoaffiliaterepcode">Rep Code</label>
					<div class="input-box">
						<input type="text" name="neoaffiliaterepcode" class="input-text" id="neoaffiliaterepcode" value="<?php if(!empty($repcode)): echo $repcode; else: ''; endif; ?>" readonly />
					</div>
				</div>
				<div class="field">
			        <label for="repcustomername" class="required">Customer Name</label>
			        <div class="input-box">
			            <input type="text" id="repcustomername" name="repcustomername" value="" title="Customer Name" maxlength="255" class="input-text">
			        </div>
			    </div>
			</li>
			<li class="fields">
				<div class="field">
					<label for="repemail" class="required">Customer Email Address</label>
					<div class="input-box">
						<input type="text" name="repemail" id="repemail" value="" title="Customer Email Address" class="input-text validate-email">
					</div>
				</div>
				<div class="field">
					<label for="repmobile" class="required">Customer Mobile</label>
					<div class="input-box">
						<input type="text" name="repmobile" value="" title="Customer Mobile" class="input-text validate-length maximum-length-10 minimum-length-10 validate-digits" id="repmobile">
					</div>
				</div>
			</li>
		</ul>
	</form>
</div>
<?php endif; ?>