<div>	
	<h3><?php echo $this->__('Shipping Address')?></h3>
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
       <li class="wide">
           <label for="shipping-address-select" class="notice"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
           <div class="input-box">
               <?php echo $this->getAddressesHtmlSelect('shipping') ?>
           </div>
       </li>
    <?php endif ?>
        <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
            <fieldset>
                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                <ul>
                    <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->toHtml() ?></li>
                    <!--li class="fields">
                        <div class="fields">
                            <label for="shipping:company"><?php //echo $this->__('Company') ?></label>
                            <div class="input-box">
                                <input type="text" id="shipping:company" name="shipping[company]" value="<?php //echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php //echo $this->__('Company') ?>" class="input-text <?php //echo $this->helper('opc')->getAttributeValidationClass('company') ?>"/>
                            </div>
                        </div>
                    </li-->
					<li class="fields">
						<div class="field">
                            <label for="shipping:postcode" class="required"><em style="display: block;">*</em><?php echo $this->__('Pincode') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('Pincode') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text shipping-postcode validate-zip-international <?php echo $this->helper('opc')->getAttributeValidationClass('postcode') ?>" onchange="sendPincode_Shipping(this.value);" />
                            </div>
                        </div>
						<div class="field">
                            <label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                            <div class="input-box">
                                <input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" />
                            </div>
                        </div>
					</li>

                    <?php

                        $storename = 'Store Name';

                        if(Mage::getSingleton('checkout/session')->getMicrosoftDiscountRedirect() == 1){
                          $storename = 'Institute Name';
                        }

                      ?>
                      
                    <li class="wide">
                        <?php 
                            $validation_class = $this->helper('customer/address')->getAttributeValidationClass('company') ;
                            $required = strstr($validation_class, 'required-entry');
                        ?>
                        <label for="company" class=<?php echo $required?"required":""?>><?php echo $this->__($storename) ?> <?php echo $required?"<em>*</em>":""?> </label>
                        <div class="input-box">
                            <input type="text" name="shipping[company]" id="company" title="<?php echo $this->__($storename) ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="input-text <?php echo $validation_class ?> validate-alphanum-with-spaces" />
                        </div>
                    </li>

            <?php $_streetValidationClass = $this->helper('opc')->getAttributeValidationClass('street'); ?>
                    <li class="wide">
                        <label for="shipping:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <li class="wide">
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
            <?php endfor; ?>
                    <?php if ($this->helper('opc')->isVatAttributeVisible()) : ?>
                    <li class="wide">
                        <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                        <div class="input-box">
                            <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('vat_id') ?>" />
                        </div>
                    </li>
                    <?php endif; ?>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('city') ?>" id="shipping:city" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                            <div class="input-box">
                                <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('region') ?>" style="display:none;" />
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect('shipping') ?>
                            </div>
                        </div>
						<div class="field">
                            <label for="shipping:fax" class="required"><em>*</em><?php echo $this->__('Mobile') ?></label>
                            <div class="input-box">
                                <input type="text" name="shipping[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Mobile') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('fax') ?> required-entry validate-length maximum-length-10 minimum-length-10 validate-digits" id="shipping:fax"  />
                            </div>
                        </div>
                    </li>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                	<div class="clear"></div>
                    <li class="control">
                        <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" <?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                <?php endif;?>
                </ul>
            </fieldset>
        </li>
        <li class="control hidden">
            <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" class="checkbox" /><label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label>
        </li>
    </ul>

<script type="text/javascript">
//<![CDATA[
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
	jQuery(document).ready(function(){
		jQuery('.shipping-postcode').addClass('required-entry');
		jQuery('.shipping-postcode').change(function(){
			sendPincode_Shipping(jQuery(this).val());
		});
	});
	function sendPincode_Shipping(pincode){
		var numbers = /^[0-9]+$/;
		if(pincode.match(numbers))
		{  
			var actionurl = '<?php  echo  Mage::getBaseUrl()."custom/index/checkPincodeState/pincode/"?>' + pincode ;
			//var myDynamicAction1 = actionurl.replace("http://","https://");
			var myDynamicAction1 = actionurl.replace("http://","http://");
			http_dynamic1 = new XMLHttpRequest(); 
			http_dynamic1.open("POST", myDynamicAction1, true);
			http_dynamic1.send(null);
			http_dynamic1.onreadystatechange = function() {
				if (http_dynamic1.readyState == 4) {
				
					var state_data = http_dynamic1.responseText;
					if(state_data != "ERROR"){
						var state_data_array = state_data.split("$$$$");
						var state_id = state_data_array[0];
						var state_code = state_data_array[1];
						
						/* Assign State value in Drop Box*/
						document.getElementById("shipping:region_id").value= state_id;
						
						var actionurl2 = '<?php  echo  Mage::getBaseUrl()."custom/index/checkPincodeStateCities/pincode/"?>' + pincode ;
						//var myDynamicAction2 = actionurl2.replace("http://","https://");
						var myDynamicAction2 = actionurl2.replace("http://","http://");
						http_dynamic2 = new XMLHttpRequest(); 
						http_dynamic2.open("POST", myDynamicAction2, true);
						http_dynamic2.send(null);
						http_dynamic2.onreadystatechange = function() {
						
							if (http_dynamic2.readyState == 4) {
								var city_name  = http_dynamic2.responseText ;
								if(city_name){
									/* Assign City value in Text Box*/
									document.getElementById("shipping:city").value= city_name;
								}else{
									document.getElementById("shipping:city").value= '';
								}
							}
						}
					}else{
						alert("Sorry , we do not have service for this Pincode , you can try with alternate Delivery Address to complete your purchase");
						document.getElementById("shipping:postcode").value= '';
						document.getElementById("shipping:region_id").value= '';
						document.getElementById("shipping:city").value= '';
					}
				}
			}
		}
		else  
		{   /* Wrong Pincode validation */
			alert('Pincode must have numeric characters only.');
			document.getElementById("shipping:postcode").focus();
			document.getElementById("shipping:postcode").value = '';
			document.getElementById("shipping:region_id").value= '';
			document.getElementById("shipping:city").value= '';
			return false;  
		}
	}
//]]>
</script>
</div>