<div class="messageContainer">
	<div class="errorContainer">
        <h1> <span>OHHHHH!!!!</span></h1>
        <p>Your Number is already registered.</p>
        <!-- <p>For further queries contact support@electronicsbazaar.com or call us at 1800-266-4000</p> --> 
        <div class="successImg"></div>
        <a href="<?php echo $this->getBaseUrl().'one-day-super-sale'; ?>" > GO BACK </a>
    </div>
</div>

