<?php /* @var $this Fooman_GoogleAnalyticsPlus_Block_Universal */?>
<?php if ($this->shouldInclude()): ?>
    <?php $altUniversal = $this->getAlternativeUniversalAccount(); ?>
    <!-- Google Analytics -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','<?php echo $this->getAnalyticsLocation(); ?>','ga');

        ga('create', '<?php echo $this->getUniversalAccount(); ?>',<?php echo $this->getUniversalParams(); ?>);
        <?php if ($altUniversal):?>
            ga('create', '<?php echo $altUniversal; ?>',<?php echo $this->getUniversalParams(true); ?>);
        <?php endif;?>

        <?php if($this->getUniversalAnonymise()):?>
            ga('set', 'anonymizeIp', true);
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.set', 'anonymizeIp', true);
            <?php endif;?>
        <?php endif;?>
        <?php if($this->getUniversalDisplayAdvertising()):?>
            ga('require', 'displayfeatures'<?php if($this->getUniversalDisplayAdvertisingCookieName()):?>, undefined, { cookieName: '<?php echo $this->getUniversalDisplayAdvertisingCookieName(); ?>' }<?php endif; ?>);
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.require', 'displayfeatures'<?php if($this->getUniversalDisplayAdvertisingCookieName()):?>, undefined, { cookieName: '<?php echo $this->getUniversalDisplayAdvertisingCookieName(); ?>' }<?php endif; ?>);
            <?php endif;?>
        <?php endif;?>
        ga('send', 'pageview', '<?php echo $this->getPageName(); ?>');
        <?php if ($altUniversal):?>
            ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.send', 'pageview', '<?php echo $this->getPageName(); ?>');
        <?php endif;?>

    </script>
    <?php if($this->isSuccessPage()):?>
        <?php $order = $this->_getOrder();?>
        <script>
            /* <![CDATA[ */
        ga('require', 'ecommerce', 'ecommerce.js');
        <?php if ($altUniversal):?>
            ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.require', 'ecommerce', 'ecommerce.js');
        <?php endif;?>

            <?php 
            $shipping = Mage::helper('googleanalyticsplus')->convert($order, 'shipping_amount');
            $tax = Mage::helper('googleanalyticsplus')->convert($order, 'tax_amount');
            $revenue =  Mage::helper('googleanalyticsplus')->convert($order, 'grand_total');
            $revenue -= (($this->shouldExcludeShipping())? $shipping : 0);
            $revenue -= (($this->shouldExcludeTax())? $tax : 0);
            
            $transactionDetails = "{
            'id': '". $this->jsQuoteEscape($order->getIncrementId()) ."',
            'affiliation': '". $this->jsQuoteEscape(Mage::app()->getStore()->getName()) ."',
            'revenue': '". $revenue ."',
            'shipping': '". $shipping ."',
            'tax': '". $tax ."',
            'currency': '". Mage::helper('googleanalyticsplus')->getTrackingCurrency($order) ."'
            }";
            ?>

        ga('ecommerce:addTransaction', <?php echo $transactionDetails?>);
        <?php if ($altUniversal):?>
            ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.ecommerce:addTransaction', <?php echo $transactionDetails?>);
        <?php endif;?>


        <?php foreach ($order->getAllVisibleItems() as $item):?>

            <?php $itemDetails = "{
                'id': '".$this->jsQuoteEscape($order->getIncrementId()) ."',
                'name': '". $this->jsQuoteEscape($item->getName()) ."',
                'sku': '". $this->jsQuoteEscape($item->getSku()) ."',
                'price': '". Mage::helper('googleanalyticsplus')->convert($item, 'price', $order->getOrderCurrencyCode()) ."',
                'quantity': '". (int)$item->getQtyOrdered() ."',
                'category': '". $this->jsQuoteEscape($this->getCategory($item)) ."'
                }";
                ?>


            ga('ecommerce:addItem', <?php echo $itemDetails?>);
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.ecommerce:addItem', <?php echo $itemDetails?>);
            <?php endif;?>
        <?php endforeach;?>
        ga('ecommerce:send');
        <?php if ($altUniversal):?>
            ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.ecommerce:send');
        <?php endif;?>
            /* ]]> */
        </script>
    <?php endif; ?>
    <!-- End Google Analytics -->
<?php endif; ?>
<!-- Start Alexa Certify Javascript -->   
<script type="text/javascript">
_atrk_opts = { atrk_acct:"X6awo1IWx810V1", domain:"electronicsbazaar.com",dynamic: true};
(function() { var as = document.createElement('script'); as.type = 'text/javascript'; as.async = true; as.src = "https://d31qbv1cthcecs.cloudfront.net/atrk.js"; var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(as, s); })();
</script>
<noscript><img src="https://d5nxst8fruw4z.cloudfront.net/atrk.gif?account=X6awo1IWx810V1" style="display:none" height="1" width="1" alt="" /></noscript>
<!-- End Alexa Certify Javascript -->

<!-- Facebook Pixel Code -->

<script>

  !function(f,b,e,v,n,t,s)

  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?

  n.callMethod.apply(n,arguments):n.queue.push(arguments)};

  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';

  n.queue=[];t=b.createElement(e);t.async=!0;

  t.src=v;s=b.getElementsByTagName(e)[0];

  s.parentNode.insertBefore(t,s)}(window, document,'script',

  'https://connect.facebook.net/en_US/fbevents.js');

  fbq('init', '180825159101997');

  fbq('track', 'PageView');

</script>

<noscript><img height="1" width="1" style="display:none"

  src="https://www.facebook.com/tr?id=180825159101997&ev=PageView&noscript=1"

/></noscript>

<!-- End Facebook Pixel Code -->
