<div class="deals-container">
  <div class="deals-list-content">
  <div class="deals-heading"><img src="http://cdn.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/big-bang-sale-heading.png" alt=""></div>
  <div class="sale-list-container">
    <div class="sale-list-heading"><h1>Open Box Mobile</h1></div>
    <ul class="clearfix">
        <li class="clearfix">
                <div class="deal-image"><a href="http://www.electronicsbazaar.com/samsung-galaxy-j7-black-16-gb" target="_blank"><span><img src="http://cdn.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/deals-images//samsung-j7.jpg"></span></a></div>
                <div class="deal-content">
                        <p class="title"><a href="http://www.electronicsbazaar.com/samsung-galaxy-j7-black-16-gb" target="_blank">Samsung Galaxy J7 <span class="price">Rs. 10850/-</span></a></p>
                        <div class="buy-now-btn"><a href="http://www.electronicsbazaar.com/samsung-galaxy-j7-black-16-gb" target="_blank">Buy Now</a></div>
                </div>
        </li>
        <li class="clearfix">
                <div class="deal-image"><a href="http://www.electronicsbazaar.com/samsung-galaxy-j5-black-8-gb" target="_blank"><span><img src="http://cdn.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/deals-images//samsung-j5.jpg"></span></a></div>
                <div class="deal-content">
                        <p class="title"><a href="http://www.electronicsbazaar.com/samsung-galaxy-j5-black-8-gb" target="_blank">Samsung Galaxy J5 <span class="price">@ 8450/-</span></a></p>
                        <div class="buy-now-btn"><a href="http://www.electronicsbazaar.com/samsung-galaxy-j5-black-8-gb" target="_blank">Buy Now</a></div>
                </div>
        </li>

        <li class="clearfix">
                <div class="deal-image"><a href="http://www.electronicsbazaar.com/samsung-galaxy-on7-black-8-gb" target="_blank"><span><img src="http://cdn.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/deals-images//samsung-on7.jpg"></span></a></div>
                <div class="deal-content">
                        <p class="title"><a href="http://www.electronicsbazaar.com/samsung-galaxy-on7-black-8-gb" target="_blank">Samsung Galaxy On7 <span class="price">@ 7250/-</span></a></p>
                        <div class="buy-now-btn"><a href="http://www.electronicsbazaar.com/samsung-galaxy-on7-black-8-gb" target="_blank">Buy Now</a></div>
                </div>
            </li>

        <li class="clearfix">
                <div class="deal-image"><a href="http://www.electronicsbazaar.com/samsung-galaxy-j7-6-new-2016-edition-black-16-gb-7526" target="_blank"><span><img src="http://cdn.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/deals-images//samsung-j7.jpg"></span></a></div>
                <div class="deal-content">
                        <p class="title"><a href="http://www.electronicsbazaar.com/samsung-galaxy-j7-6-new-2016-edition-black-16-gb-7526" target="_blank">Samsung Galaxy J7 - 6 (New 2016 Edition) <span class="price">@ 12600/-</span></a></p>
                        <div class="buy-now-btn"><a href="http://www.electronicsbazaar.com/samsung-galaxy-j7-6-new-2016-edition-black-16-gb-7526" target="_blank">Buy Now</a></div>
                </div>
            </li>

        <li class="clearfix">
                <div class="deal-image"><a href="http://www.electronicsbazaar.com/samsung-galaxy-j5-black-8-gb-9213" target="_blank"><span><img src="http://cdn.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/deals-images//samsung-j5-new.jpg"></span></a></div>
                <div class="deal-content">
                        <p class="title"><a href="http://www.electronicsbazaar.com/samsung-galaxy-j5-black-8-gb-9213" target="_blank">Samsung Galaxy J5 - 6 (New 2016 Edition) <span class="price">@ 9650/-</span></a></p>
                        <div class="buy-now-btn"><a href="http://www.electronicsbazaar.com/samsung-galaxy-j5-black-8-gb-9213" target="_blank">Buy Now</a></div>
                </div>
            </li>

        <li class="clearfix">
                <div class="deal-image"><a href="http://www.electronicsbazaar.com/moto-g-plus-4th-gen-black-32-gb" target="_blank"><span><img src="http://cdn.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/deals-images//moto-g4-plus-32.jpg"></span></a></div>
                <div class="deal-content">
                        <p class="title"><a href="http://www.electronicsbazaar.com/moto-g-plus-4th-gen-black-32-gb" target="_blank">Moto G 4 Plus 32 GB <span class="price">@ 10800/-</span></a></p>
                        <div class="buy-now-btn"><a href="http://www.electronicsbazaar.com/moto-g-plus-4th-gen-black-32-gb" target="_blank">Buy Now</a></div>
                </div>
            </li>

        <li class="clearfix">
                <div class="deal-image"><a href="http://www.electronicsbazaar.com/moto-g-3rd-generation-black-16-gb-7656" target="_blank"><span><img src="http://cdn.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/deals-images//moto-g4-plus-16.jpg"></span></a></div>
                <div class="deal-content">
                        <p class="title"><a href="http://www.electronicsbazaar.com/moto-g-3rd-generation-black-16-gb-7656" target="_blank">Moto G 4 Plus 16 GB <span class="price">@ 9550/-</span></a></p>
                        <div class="buy-now-btn"><a href="http://www.electronicsbazaar.com/moto-g-3rd-generation-black-16-gb-7656" target="_blank">Buy Now</a></div>
                </div>
            </li>

        <li class="clearfix">
                <div class="deal-image"><a href="http://www.electronicsbazaar.com/moto-g-3rd-generation-black-16-gb-7658" target="_blank"><span><img src="http://cdn.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/deals-images//moto-g4-16.jpg"></span></a></div>
                <div class="deal-content">
                        <p class="title"><a href="http://www.electronicsbazaar.com/moto-g-3rd-generation-black-16-gb-7658" target="_blank">Moto G 4 16 GB <span class="price">@ 8800/-</span></a></p>
                        <div class="buy-now-btn"><a href="http://www.electronicsbazaar.com/moto-g-3rd-generation-black-16-gb-7658" target="_blank">Buy Now</a></div>
                </div>
            </li>
            </ul>
            </div>

            <div class="sale-list-container">
                <div class="sale-list-heading"><h1>Seal Packed Mobile</h1></div>
                    <ul class="clearfix">
                    <li class="clearfix">
                        <div class="deal-image"><a href="http://www.electronicsbazaar.com/one-plus-3-soft-gold-64-gb" target="_blank"><span><img src="http://cdn.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/deals-images//one-plus-3.jpg"></span></a></div>
                        <div class="deal-content">
                                <p class="title"><a href="http://www.electronicsbazaar.com/one-plus-3-soft-gold-64-gb" target="_blank">One Plus 3 <span class="price">@ 26990/-</span></a></p>
                                <div class="buy-now-btn"><a href="http://www.electronicsbazaar.com/one-plus-3-soft-gold-64-gb" target="_blank">Buy Now</a></div>
                        </div>
                    </li>

                <li class="clearfix">
                        <div class="deal-image"><a href="http://www.electronicsbazaar.com/moto-g-4th-gen-black-16gb-8720" target="_blank"><span><img src="http://cdn.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/deals-images//moto-g-play.jpg"></span></a></div>
                        <div class="deal-content">
                                <p class="title"><a href="http://www.electronicsbazaar.com/moto-g-4th-gen-black-16gb-8720" target="_blank">Moto G Play <span class="price">@ 8400/-</span></a></p>
                                <div class="buy-now-btn"><a href="http://www.electronicsbazaar.com/moto-g-4th-gen-black-16gb-8720" target="_blank">Buy Now</a></div>
                        </div>
                    </li>

                <li class="clearfix">
                        <div class="deal-image"><a href="http://www.electronicsbazaar.com/coolpad-note-3-plus-champagne-white" target="_blank"><span><img src="http://cdn.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/deals-images//cool-pad-note-3.jpg"></span></a></div>
                        <div class="deal-content">
                                <p class="title"><a href="http://www.electronicsbazaar.com/coolpad-note-3-plus-champagne-white" target="_blank">Cool Pad Note 3 <span class="price">@ 8400/-</span></a></p>
                                <div class="buy-now-btn"><a href="http://www.electronicsbazaar.com/coolpad-note-3-plus-champagne-white" target="_blank">Buy Now</a></div>
                        </div> 
                    </li>

                <li class="clearfix">
                        <div class="deal-image"><a href="http://www.electronicsbazaar.com/coolpad-mega-2-5d-royal-gold" target="_blank"><span><img src="http://cdn.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/deals-images//cool-pad-mega.jpg"></span></a></div>
                        <div class="deal-content">
                                <p class="title"><a href="http://www.electronicsbazaar.com/coolpad-mega-2-5d-royal-gold" target="_blank">Cool Pad Mega <span class="price">@ 6800/-</span></a></p>
                                <div class="buy-now-btn"><a href="http://www.electronicsbazaar.com/coolpad-mega-2-5d-royal-gold" target="_blank">Buy Now</a></div>
                        </div>
                    </li>

                <li class="clearfix">
                        <div class="deal-image"><a href="http://www.electronicsbazaar.com/micromax-cg666-white" target="_blank"><span><img src="http://cdn.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/deals-images//micromax-cg-666.jpg"></span></a></div>
                        <div class="deal-content">
                                <p class="title"><a href="http://www.electronicsbazaar.com/micromax-cg666-white" target="_blank">Micromax CG 666 <span class="price">@ 1475/-</span></a></p>
                                <div class="buy-now-btn"><a href="http://www.electronicsbazaar.com/micromax-cg666-white" target="_blank">Buy Now</a></div>
                        </div>
                    </li>
            </ul>
        </div>
  </div>
</div> 