	<?php /*$items = $this->getItems()->getData(); ?>
	<?php if(count($items) > 0): ?>
	<div class="add-to-compare-list clearfix">
			  	<ul class="clearfix">

		<?php foreach($this->getItems() as $item): ?>
		
			    <li>
			    	<a href="#">
			    		<img src="<?php echo $this->helper('catalog/image')->init($item, 'small_image')->resize(125, 125); ?>" width="125" height="125" alt="<?php echo $this->stripTags($item->getName(), null, true) ?>" />   
			    	</a>
			    </li>

		<?php endforeach; ?>


			  	</ul>
				<a href="http://www.electronicsbazaar.com/catalog/product_compare" class="btn-add-to-compare">Compare Now</a>
			</div>
	<?php endif; */  ?> 