<div class="compare-container">
    <div class="compare-table-container">
    <table>
    <tbody>
            <tr>
                <td>Add new product to compare</td>
                <td>
                    <div class="compare-search-container clearfix">
                    <div class="input-box"><input placeholder="Product Name" type="text"></div>
                    <input value="Add" type="button">
                    </div>
                </td>
                <td>
                    <div class="compare-search-container clearfix">
                    <div class="input-box"><input placeholder="Product Name" type="text"></div>
                    <input value="Add" type="button">
                    </div>
                </td>
                <td>
                    <div class="compare-search-container clearfix">
                    <div class="input-box"><input placeholder="Product Name" type="text"></div>
                    <input value="Add" type="button">
                    </div>
                </td>
            </tr>
            <tr>
                <td>Product</td>
                <td align="center" class="product-image-container">
                    <a class="close-button"><i class="fa fa-close"></i></a>
                    <div class="compare-image"><a><span><img src="http://cdn.electronicsbazaar.com/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/h/e/hero-blue_carousel_1.jpg" /></span></a></div>
                    <div class="actions ">
                        <ul class="add-to-links">
                            <li><a href="http://www.electronicsbazaar.com/wishlist/index/add/product/2283/form_key/uU8ylpt7fneBpJYT/" class="link-wishlist " title="Add to Wishlist">Add to Wishlist</a></li>
                            <li><button class="button btn-cart" title="Buy now" type="button" onclick="setLocation('http://www.electronicsbazaar.com/checkout/cart/add/uenc/aHR0cDovL3d3dy5lbGVjdHJvbmljc2JhemFhci5jb20vbGFwdG9wcw,,/product/2283/form_key/uU8ylpt7fneBpJYT/')" oldevent="setLocation('http://www.electronicsbazaar.com/checkout/cart/add/uenc/aHR0cDovL3d3dy5lbGVjdHJvbmljc2JhemFhci5jb20vbGFwdG9wcw,,/product/2283/form_key/uU8ylpt7fneBpJYT/')">
                        <span><span>Buy now</span></span></button></li>
                        </ul>
                    </div>
                </td>
                <td align="center" class="product-image-container">
                    <a class="close-button"><i class="fa fa-close"></i></a>
                    <div class="compare-image"><a><span><img src="http://cdn.electronicsbazaar.com/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/h/e/hero-blue_carousel_1.jpg" /></span></a></div>
                    <div class="actions ">
                        <ul class="add-to-links">
                            <li><a href="http://www.electronicsbazaar.com/wishlist/index/add/product/2283/form_key/uU8ylpt7fneBpJYT/" class="link-wishlist " title="Add to Wishlist">Add to Wishlist</a></li>
                            <li><button class="button btn-cart" title="Buy now" type="button" onclick="setLocation('http://www.electronicsbazaar.com/checkout/cart/add/uenc/aHR0cDovL3d3dy5lbGVjdHJvbmljc2JhemFhci5jb20vbGFwdG9wcw,,/product/2283/form_key/uU8ylpt7fneBpJYT/')" oldevent="setLocation('http://www.electronicsbazaar.com/checkout/cart/add/uenc/aHR0cDovL3d3dy5lbGVjdHJvbmljc2JhemFhci5jb20vbGFwdG9wcw,,/product/2283/form_key/uU8ylpt7fneBpJYT/')">
                        <span><span>Buy now</span></span></button></li>
                        </ul>
                    </div>
                </td>
                <td align="center" class="product-image-container">
                    <a class="close-button"><i class="fa fa-close"></i></a>
                    <div class="compare-image"><a><span><img src="http://cdn.electronicsbazaar.com/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/h/e/hero-blue_carousel_1.jpg" /></span></a></div>
                    <div class="actions ">
                        <ul class="add-to-links">
                            <li><a href="http://www.electronicsbazaar.com/wishlist/index/add/product/2283/form_key/uU8ylpt7fneBpJYT/" class="link-wishlist " title="Add to Wishlist">Add to Wishlist</a></li>
                            <li><button class="button btn-cart" title="Buy now" type="button" onclick="setLocation('http://www.electronicsbazaar.com/checkout/cart/add/uenc/aHR0cDovL3d3dy5lbGVjdHJvbmljc2JhemFhci5jb20vbGFwdG9wcw,,/product/2283/form_key/uU8ylpt7fneBpJYT/')" oldevent="setLocation('http://www.electronicsbazaar.com/checkout/cart/add/uenc/aHR0cDovL3d3dy5lbGVjdHJvbmljc2JhemFhci5jb20vbGFwdG9wcw,,/product/2283/form_key/uU8ylpt7fneBpJYT/')">
                        <span><span>Buy now</span></span></button></li>
                        </ul>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Name</td>
                <td>Laptop 1</td>      
                <td>Laptop 2</td>
                <td>Laptop 3</td>
            </tr>
            <tr>
                <td>Price</td>
                <td>Price1</td>
                <td>Price2</td>
                <td>Price3</td>
            </tr>
        </tbody>
    </table>
    </div>
</div>