<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter_Abstract
 */
?>
<ol>
    <?php foreach ($this->getItems() as $_item): ?>
        <li>
            
            <?php $_img = $this->helper('attributeimage')->getAttributeImage($_item->getValue()); ?>
            <?php if ($_img && $_item->getFilter()->getRequestVar() != 'cat'): ?>
                <img src="<?php echo $this->escapeHtml($_img); ?>" alt="<?php echo $_item->getLabel(); ?>" />
            <?php endif; ?>
            <?php if ($_item->getCount() > 0): ?>
                <a href="<?php echo $this->urlEscape($_item->getUrl()); ?>"><?php echo $_item->getLabel(); ?></a>
            <?php else: echo $_item->getLabel(); ?>
            <?php endif; ?>
            <?php if ($this->shouldDisplayProductCount()): ?>
                (<?php echo $_item->getCount(); ?>)
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>


<?php echo $_img = $this->helper('attributeimage')->getAttributeImage(3);



$attributeId = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product','color');
    $attr = Mage::getModel('catalog/resource_eav_attribute')->load($attributeId);
    if ($attr->usesSource()) {

    $attributeOptions = $attr ->getSource()->getAllOptions();

    foreach ($attributeOptions as $option) {
        //if($option['label']=='Purple'){
           echo "<br>".$curattributeid=$option['value'];
        //}
      }

    }

 ?>
