<?php
   $skinUrl = $this->getSkinUrl();
   $basenUrl = $this->getBaseUrl();
?>
 
<div class="gadgetModuleContainer">
     <h1>Choose By <span class="color">Brands</span></h1>
     <!--ul class="brandsList">
         <li>
             <div class="imgContent"><a href="<?php //echo $basenUrl.'gadget/mobile/apple'; ?>"><img src="<?php //echo $skinUrl.'gadget/images/mobile/iphone.jpg'?>" alt="iPhone"></a></div>
             <p><a href="<?php //echo $basenUrl.'gadget/mobile/apple'; ?>">Apple iPhone</a></p>
         </li>
     </ul--> 
     <ul class="brandsList">
            <li>
                <div class="imgContent"><a href="<?php echo $basenUrl.'gadget/mobile/apple'; ?>"><img alt="iPhone" src="<?php echo $skinUrl.'gadget/images/mobile/iphone.jpg'?>"></a></div>
                <p><a href="<?php echo $basenUrl.'gadget/mobile/apple'; ?>">Apple iPhone</a></p>
            </li>
            <li>
                <div class="imgContent"><a href="<?php echo $basenUrl.'gadget/mobile/samsung'; ?>"><img alt="Samsung" src="<?php echo $skinUrl.'gadget/images/mobile/samsung.png'?>"></a></div>
                <p><a href="<?php echo $basenUrl.'gadget/mobile/samsung'; ?>">Samsung</a></p>
            </li>

        </ul> 
</div>