
<div class="new-gadget-container new-gadget-lenovo">
    <div class="new-gadget-content">
       
        <!--gadget-home-page-banner start-->
        <div class="gadget-lenovo-home-page-banner">
            <img src="<?php echo $this->getBaseUrl(); ?>skin/frontend/rwd/ebtronics/images/gadget-lenovo-page-banner.jpg" alt="Banner1">
          
        </div>
        <!--gadget-home-page-banner ends-->
        
<!--        lenovo images-->
        <div class="lenovo-img">
           <h2 class="default-head2">Disqualified Machines</h2>
            <ul>
                <li>
                   <p>Power Port broken</p>
                    <img src="<?php echo $this->getBaseUrl(); ?>skin/frontend/rwd/ebtronics/images/power-port-broken1.png" alt="">
                    <img src="<?php echo $this->getBaseUrl(); ?>skin/frontend/rwd/ebtronics/images/power-port-broken2.png" alt="">
                </li>
                
                <li>
                   <p>Watermark/Liquid on Screen</p>
                    <img src="<?php echo $this->getBaseUrl(); ?>skin/frontend/rwd/ebtronics/images/WatermarkLiquid-on-Screen1.png" alt="">
                    <img src="<?php echo $this->getBaseUrl(); ?>skin/frontend/rwd/ebtronics/images/WatermarkLiquid-on-Screen2.png" alt="">
                </li>
                
                <li>
                   <p>Blur &amp; Discoloration</p>
                    <img src="<?php echo $this->getBaseUrl(); ?>skin/frontend/rwd/ebtronics/images/blur-discoloration1.png" alt="">
                    <img src="<?php echo $this->getBaseUrl(); ?>skin/frontend/rwd/ebtronics/images/blur-discoloration2.png" alt="">
                </li>
                
                <li>
                   <p>Screen Broken &amp; Spots</p>
                    <img src="<?php echo $this->getBaseUrl(); ?>skin/frontend/rwd/ebtronics/images/screen-broken-spots1.png" alt="">
                    <img src="<?php echo $this->getBaseUrl(); ?>skin/frontend/rwd/ebtronics/images/screen-broken-spots2.png" alt="">
                </li>
            </ul>
            <hr>
            <p>Damaged laptops (Broken Hardware, missing keys, missing battery)</p>
            <ul>
                <li><img src="<?php echo $this->getBaseUrl(); ?>skin/frontend/rwd/ebtronics/images/damaged-laptops1.png" alt=""></li>
                <li><img src="<?php echo $this->getBaseUrl(); ?>skin/frontend/rwd/ebtronics/images/damaged-laptops2.png" alt=""></li>
                <li><img src="<?php echo $this->getBaseUrl(); ?>skin/frontend/rwd/ebtronics/images/damaged-laptops3.png" alt=""></li>
                <li><img src="<?php echo $this->getBaseUrl(); ?>skin/frontend/rwd/ebtronics/images/damaged-laptops4.png" alt=""></li>
            </ul>
            
            
        </div>
        
        <div class="pdf-lenovo">
            <a href="<?php echo $this->getBaseUrl(); ?>media/lenovoprogram/Buyback-offer.pdf" target="_blank">Click Here to Download Detailed T&C</a>
        </div>
        
        <h2 class="default-head2">Terms &amp; Conditions</h2>
        <ul class="list-content">
            <li>The offer is valid only on laptops.</li>
            <li>Exchange value of old laptop will be based upon configuration and condition.</li>
            <li>Customer needs to verify that he/she is the legal owner of the laptop: Customer will be asked to fill a declaration form as a proof of sale.</li>
            <li>No claims of ownership of laptop, any hardware or software present in the machine can be made once laptop is traded. Customer must take necessary back up of data.</li>
            <li>All security locks like passcode, fingerprint, and facial recognition should be removed by customer.</li>
            <li>The device should be in Working and Non – Damaged condition as defined below</li>
            
            <li class="list-head">Working
                <p>– Product must switch on</p>
                <p>– All controls and inputs should perform desired function</p>
                <p>– Battery must consume power</p>
            </li>
            
            <li class="list-head">Non-Damaged
                <p> – Device to be intact with no damage to display or body</p>
                <p>– Accessories like charger and battery must be provided</p>
            </li>            
            
            <li>Following devices should be disqualified for exchange offer
                <p> – Damaged Display due to:</p>
                <p> – Crack, Liquid Damage, Dots and Spots on display, Discoloration , Blur &amp; Lines</p>
            </li>
            
            <li>Packaging to be done in tamper proof material like bubble wrap, foam sheets and laptop box pack (Provided by E-Bazaar)</li>
            <li>Doorstep Quality Check will be performed by representatives of the Organizer.</li>
            
            <li>Doorstep QC will be performed for following elements
                <p> – Processor</p>
                <p>– Working Condition (Working / Non-Working)</p>
                <p>– RAM</p>
                <p>– Brand</p>
                <p>– Serial Number</p>
            </li>
        </ul>

    </div>
</div>
