      <div class="new-gadget-popup-container popup-laptop">
      		<div class="new-gadget-popup-inner-content">
      			<span class="new-gadget-close-popup">X</span>
      			<h1>How to find Serial Number?</h1>
      			<ul>
      				<li>
      					<h2>Guide to Find serial number (Laptops other than Apple)</h2>
      					<p><strong>Option 1</strong><br>
      					Find Serial Number printed on the rear surface of Laptop.</p>
      					<p><strong>Option 2</strong><br>
      						Press Start -> Type "Run" -> Type "CMD" ->Type "WMIC BIOS GET SERIALNUMBER" ->Press Enter</p><!-- 
                                    <span><img title="ios_serial_number" src="<?php //echo $this->getUrl().'media/sellurgadget/serial_number_ios.png'?>"/></span>   -->    
      				</li>
      				<li>
      					<h2>Guide to Find Serial Number and Year Generation (Apple)</h2>
      					<p><strong>Option 1</strong><br>
      					Serial number is printed on the rear surface of Macbook</p>
      					<p><strong>Option 2</strong><br>
      						The window that appears lists your computer's model name--for example, MacBook Air (13-inch, Early 2015)--and serial number.
      					</p><!-- 
                                    <span><img title="windows_serial_number" src="<?php //echo $this->getUrl().'media/sellurgadget/serial_number_windows.png'?>"/></span>   -->
      				</li>
      			</ul>
      			<div class="gadget-icon"><img src="<?php echo $this->getSkinUrl(); ?>images/ebt/gadget-laptop-icon.png"></div>
      		</div>
      </div>
	<div class="new-gadget-popup-container popup-mobile">
		<div class="new-gadget-popup-inner-content">
			<span class="new-gadget-close-popup">X</span>
			<h1>How  to find IMEI Number ?</h1>
			<ul>
				<li>
					<h2>How to find Imei Number on Android ?</h2>
					<p>Open the Android Settings menu>Tap "About Phone"> Tap "Status"<br>
						OR<br>
						Open the dialer on your phone and type *#06# using the keypad
					</p>
				</li>
				<li>
					<h2>How to find Imei Number on iPhone ?</h2>
					<p>Open the Apple Settings on the phone > Tap “General” > Tap “About”<br>
						OR<br>
					Open the dialer on your phone and type *#06# using the keypad</p>
				</li>
			</ul>
			<div class="gadget-icon"><img src="<?php echo $this->getSkinUrl(); ?>images/ebt/gadget-mobile-icon.png"></div>
		</div>
	</div>