<?php
   $skinUrl  = $this->getSkinUrl();
   $basenUrl = $this->getBaseUrl();
?>
<div class="mobileContainer">
	<h1>Apple iPhone</h1>
	<ul>
    	<li>
        	<div class="productImg">
        		<a href="<?php echo $basenUrl.'gadget/mobile/applephone/sku/1234'; ?>"> 
        			<img src="<?php echo $skinUrl.'gadget/images/mobile/apple/iphone.png'?>" alt="iPhone" />
        		</a>
        	</div>
            <div class="productContent">
	            <div class="productContentInner"> 
	            	<p>Apple iPhone4</p>
	            </div>
            </div>
        </li>
        <li>
        	<div class="productImg">
        		<a href="<?php echo $basenUrl.'gadget/mobile/applephone'; ?>">
        			<img src="<?php echo $skinUrl.'gadget/images/mobile/apple/iphone.png'?>" alt="iPhone" />
        			</a>
        	</div>
            <div class="productContent">
            	<div class="productContentInner">
            		<p>Lava Iris 408e (Frosted Silver, 115 MB)</p>
            	</div>
            </div>
        </li>
        <li>
        	<div class="productImg">
        		<a href="<?php echo $basenUrl.'gadget/mobile/applephone'; ?>">
        			<img src="<?php echo $skinUrl.'gadget/images/mobile/apple/iphone.png'?>" alt="iPhone" />
        		</a>
        	</div>
            <div class="productContent">
            	<div class="productContentInner">
            		<p>Samsung Galaxy Note 3 Neo Dual SIM</p>
            	</div>
            </div>
        </li>
    </ul>
</div>