<?php

    $brand = $this->getRequest()->getActionName(); 
    $catagory = $this->getRequest()->getControllerName(); 

    $products = $this->helper('gadget')->getBrandedGadgetsCollection(ucfirst($brand),ucfirst($catagory));
    
?>


<div class="gadgetModuleContainer brand-list-container">
     <h1><?php echo ucfirst(Mage::app()->getRequest()->getActionName()); ?></h1>


    <!-- <div class="brandSearch clearfix">
        <div class="inputField">
            <input type="text" class="search_box" id="search_box" placeholder="Search brand's products" autocomplete="off">
        </div>
        <button class="button" title="Search" type="submit">
            <i aria-hidden="true" class="fa fa-search"></i>
        </button>
    </div> -->

    <div id="searchres" class=""></div> 

    <ul class="mobileList clearfix">
    <!-- Start mobileList -->
        <?php foreach($products as $product): 
          //print_r($product->getData()); exit;
        $_product_id = $product->getEntityId();
         ?>
           <li>
              <div class="imgContent">
                 <!-- Start imgContent -->
                 <a href="<?php echo $product->getUrlInStore(); ?>">
                 <span><img src="<?php echo (string)Mage::helper('catalog/image')->init($product, 'image'); ?>" alt="<?php echo $product->getName(); ?>"></span>
                 </a>
              </div>
              <!-- End imgContent -->
              <div class="productContent">
                 <!-- Start productContent -->
                 <div class="title clearfix">
                    <!-- Start title -->
                    
                    <div class="heading">
                       <h2><a href="<?php echo $product->getUrlInStore(); ?>"><?php echo $product->getName(); ?></a></h2>
                    </div>
                 </div>
                 <!-- End title -->
                <div class="brand-price-content">Get Upto 
                    <span id="product-price_<?php echo $_product_id; ?>" class="brand-price">
                        <?php echo number_format($product->getPrice()); ?>
                    </span>  
                    <input type="hidden" class="brand brand_<?php echo $_product_id; ?>" value="<?php echo $product->getPrice() ?>"/>                        
                </div>

                <div class="storage-container">
                    <!-- Start storage-container -->
                    <ul class="options-list clearfix">
                        <!-- Sart options-list -->
                        <?php $customOption = Mage::helper('gadget')->getProductOptions($_product_id); ?>
                        <?php  
                            $optStr = '';
                            foreach($customOption as $optionKey => $optionVal)
                            { 
                                
                                foreach($optionVal->getValues() as $valuesKey => $valuesVal)
                                {
                                    if($optionVal->getDefaultTitle() == 'Storage'){
                                      $optStr.= "<li class='clearfix'><input type='radio' class='adio product-custom-option' data-product='".$_product_id."' name='options[".$optionVal->getId()."]' value='".$valuesVal->getPrice()."'><span class='label'>";  
                                      $optStr.= "<label>".$valuesVal->getTitle()."</label>";

                                      $optStr.= "</span></li>";
                                      
                                    }
                                }
                                echo($optStr );
                                break;                    
                                
                            }

                             
                        ?>

                    </ul>
                    <!-- End options-list -->  
                 </div>


                 <div class="btnContainer">       
                    <a href="<?php echo $product->getUrlInStore(); ?>"><span>Sell</span></a>
                 </div>

                 <!-- End storage-container -->
                </div>
              <!-- End productContent -->
           </li>
        <?php endforeach; ?>
    </ul>
    <!-- End mobileList -->

</div>


<script type="text/javascript">

var jqgs = jQuery.noConflict();
jqgs(document).ready(function()
{
    jqgs("#search_box").keyup(
        function() 
        {
            var search_string = jqgs("#search_box").val();
            if(search_string == '')
            {
                var searchres = document.getElementById("searchres");
                searchres.classList.remove("searchres");

                jqgs("#searchres").html('');
            }
        else{

            postdata = {'string' : search_string  , 'brand' :  "<?php echo $brand;?>"} 

            jqgs.post("<?php echo 'https://www.electronicsbazaar.com/neweb/index.php/gadget-new/index/searchgadget'; ?>",postdata,function(data)
            {   
                var searchres = document.getElementById("searchres");
                searchres.classList.add("searchres");

                jqgs("#searchres").html(data); 
            });
        }
    });


    jqgs("input[type=radio]").click(function(){
    if (jqgs(this).is(':checked'))
    {
      var option_price = jqgs(this).val();
      var product_id = jqgs(this).attr("data-product");
      var brandprice = jqgs('.brand_'+product_id).val();
      var newprice = parseInt(brandprice) + parseInt(option_price);
 
      //var price = parseInt();
      jqgs('#product-price_'+product_id).text((newprice).formatMoney(0, '.', ','));
    }
  });  
});

function fillme(name)
{
    var searchres = document.getElementById("searchres");
    searchres.classList.remove("searchres");

    jqgs("#search_box").val(name);
    jqgs("#searchres").html('');
}


Number.prototype.formatMoney = function(c, d, t){
var n = this, 
    c = isNaN(c = Math.abs(c)) ? 2 : c, 
    d = d == undefined ? "." : d, 
    t = t == undefined ? "," : t, 
    s = n < 0 ? "-" : "", 
    i = String(parseInt(n = Math.abs(Number(n) || 0).toFixed(c))), 
    j = (j = i.length) > 3 ? j % 3 : 0;
   return s + (j ? i.substr(0, j) + t : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : "");
 };


</script> 

