<div class="messageContainer">
	<div class="successfulContainer">
        <h1>Thank <span>You!</span></h1>
        <p>Your details have been submitted successfully.</p>
        <div class="order-id-container">Your Order ID is  <span class="order-id"><?php echo Mage::getSingleton('core/session')->getOrderId() ?></span></div>
        <div class="successImg"></div>
        <p>Please refer your email for Invoicing and Packaging Instruction</p>
        <a href="http://www.electronicsbazaar.com/gadget/" > GO BACK </a> 
    </div>
</div>