<!--div class="small-banner-container">
  <ul class="clearfix">


<li>
<a href="http://www.electronicsbazaar.com/refurbished" target="_blank"><img src="http://cdn.electronicsbazaar.com/media/homepagebanner/images/default/preowned-product.jpg" ></a>
 </li>
<li>
<a href="http://www.electronicsbazaar.com/unboxed-units" target="_blank"><img src="http://cdn.electronicsbazaar.com/media/homepagebanner/images/default/unboxed-product.jpg" ></a>  
 </li>					
  </ul>
</div-->   