<div class="main-new-banner-container clearfix">

 


<div class="flashy-banner clearfix">
 <div class="big-sale-banner clearfix">
  <a onclick="ga('send', 'event', { eventCategory: 'shopping', eventAction: 'click', eventLabel: 'big-sale-11Apr17'});"

 href="https://www.electronicsbazaar.com/deals/" alt="big-sale-11Apr17">
   <span class="star-container">
     <span class="star-animation star-animation1"><img src="https://www.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/new-banner/star.png" /></span>
     <span class="star-animation star-animation2"><img src="https://www.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/new-banner/star.png" /></span>
     <span class="star-animation star-animation3"><img src="https://www.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/new-banner/star.png" /></span>
     <span class="star-animation star-animation4"><img src="https://www.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/new-banner/star.png" /></span>
     <span class="star-animation star-animation5"><img src="https://www.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/new-banner/star.png" /></span>
     <span class="star-animation star-animation6"><img src="https://www.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/new-banner/star.png" /></span>
     <span class="star-animation star-animation7"><img src="https://www.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/new-banner/star.png" /></span>
   </span>
   <span class="buy-sale-text flash animated"><img src="https://www.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/new-banner/buy-sale.png" /></span>
   <span class="big-day-sale-text flash animated"><img src="https://www.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/new-banner/big-day-sale-text.png" /></span>
   
   <span class="twinkling"></span>
   <span class="stars"></span>   
   
   </a>  

 </div>
<div class="mobile-banner-container">
 <img src="https://www.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/new-banner/big-day-sale-mobile.jpg">
</div>
</div>

 
  

  <div class="right-side-panel">
  <div class="exciting-offers">
  <a onclick="ga('send', 'event', { eventCategory: 'shopping', eventAction: 'click', eventLabel: 'big-sale-11Apr17'});" href="https://www.electronicsbazaar.com/deals/" target="_blank">
  <img src="https://electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/new-banner/web-sticker.png" alt="deals of the day"></div>  
  </a>


  <div class="partnerprogram">
   <a href="https://www.electronicsbazaar.com/partner_program" ><img src="https://www.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/partner-program.jpg" alt="partner program"/> </a> 
   
  </div>

  <div class="coupon-code-container hourlydeals">
  <a href="https://www.electronicsbazaar.com/warranty" >
   <img src="https://electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/warranty.jpg" alt="warranty"/>
   </a>
   
  </div>
  
 </div>
</div>   


<div  class="bottom-banner-container clearfix">

<div class="small-banner-container">
  
   
  <ul class="clearfix">
   <li>
   <a href="https://www.electronicsbazaar.com/laptops/unboxed-units" target="_blank"><img src="https://www.electronicsbazaar.com/neweb/skin/frontend/rwd/electronics/customs/images/new-banner/open-box-laptop-new.jpg" alt="openbox laptops"></a>
    </li>
    <li>
   <a href="https://www.electronicsbazaar.com/mobiles/smartphones/open-box" target="_blank"><img src="https://www.electronicsbazaar.com/neweb/skin/frontend/rwd/electronics/customs/images/new-banner/open-box-mobile-new.jpg" alt="openbox mobiles"></a>  
    </li>
   <li>
   <a href="https://www.electronicsbazaar.com/laptops/refurbished" target="_blank"><img src="https://www.electronicsbazaar.com/neweb/skin/frontend/rwd/electronics/customs/images/new-banner/pre-owned-laptop-new.jpg" alt="prewoned laptop"></a>  
    </li>
     
     <li>
   <a href="https://www.electronicsbazaar.com/mobiles/smartphones/pre-owned-ref" target="_blank"><img src="https://www.electronicsbazaar.com/neweb/skin/frontend/rwd/electronics/customs/images/new-banner/pre-owned-mobile-new.jpg" alt="prewoned mobile"></a>
    </li>
   
    </ul>  
   
</div>  


<div class="bottom-right-container">
<div class="coupon-code-container">
   <a onclick="ga('send', 'event', { eventCategory: 'home-banner', eventAction: 'click', eventLabel: 'register-now'});" href="https://www.electronicsbazaar.com/customer/account/login/" target="_blank">
    <img src="https://www.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/200off.jpg" />
   </a>
  </div>

<div class="app-order-container">
    <a href="https://www.electronicsbazaar.com/download-app/" target="_blank"><span class="getextra">Get Extra</span>
    <span class="app-amount">0.5%<span class="amount-off">Off</span></span>
    <span class="allorders">for all orders through Mobile App only</span>
    <span class="download-now">Download Now!!!</span> </a>
    <a onclick="ga('send', 'event', { eventCategory: 'home-banner', eventAction: 'click', eventLabel: 'download-now'});" href="https://play.google.com/store/apps/details?id=com.electronicsbazaar.electronicsbazaar" target="_blank"><img src="https://www.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/google-play-new.png"></a>
      <a href="https://itunes.apple.com/us/app/electronicsbazaar.com/id1064879270?ls=1&mt=8" target="_blank"><img src="https://www.electronicsbazaar.com/skin/frontend/rwd/electronics/customs/images/app-store-new.png"></a>
  </div>

  </div>

</div>
  
<script type="text/javascript"> 

var jqcs = jQuery.noConflict();
 jqcs('.newDealsSlider').bxSlider({
    auto: true, 
    speed: 500,
    pause: 2000
 });
</script>

<script type="text/javascript"> 
var jqcs = jQuery.noConflict();
 jqcs('.new-slider-banner').bxSlider({
    auto: true,
    speed: 2000,
    pause: 7000,
    pager: true,
 controls: true 
 });
</script>