<?php $daily_deals = $this->getDailyDealsCollection(); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $dailycountdown = $this->getCountDownfortheDailyDeals(); ?>
<?php //echo "<pre>"; print_r($this->getWeeklyDealsCollection()->getData()); exit; ?>
<?php $weekly_deals = $this->getWeeklyDealsCollection(); ?>
<?php //echo count($weekly_deals); exit; ?>
<?php $weeklycountdown = $this->getCountDownfortheWeeklyDeals();?>
<?php $customblocks_index = new Neo_Customblocks_Block_Index(); ?>
<?php $product_list_block = new Mage_Catalog_Block_Product_List(); ?>
<?php $daily_deal_count = count($daily_deals); ?>
<?php $weekly_deal_count = count($weekly_deals); ?>

<?php #$weekly_deal_count = 0; ?>
<?php #if($daily_deal_count): ?>
<!--<div class="deals-section">
    <div class="deals-heading">
        <div class="deal-title">
            <div class="deal-icon">Deals</div>
            <span><img src="<?php #echo $this->getSkinUrl('images/deals-of-the-day.png'); ?>"></span>
        </div>
        <div class="deal-timer">
            <div class="timer-section"><?php #echo $dailycountdown; ?></div>                          
        </div>
    </div>
    <div class="deal-list-section">
        <ul class="deal-listing">
	    <?php #foreach($daily_deals as $_products): ?>
	    	<?php #$discount_percent = $customblocks_index->getDealsDiscountPercent($_products->getId()); ?>
	    	<?php //echo $discount_percent; exit; ?>
		<li class="item">
		    <div class="product-img">
			<a href="<?php #echo $_products->getProductUrl(); ?>" title="<?php #echo $this->getImageLabel($_products, 'small_image') ?>" class="product-image"><img src="<?php #echo $this->helper('catalog/image')->init($_products, 'small_image')->resize(180); ?>" /></a>
		    </div>
		    <div class="product-info-sec">
			<div class="product-name-sec">
			    <span><?php #echo $_helper->productAttribute($_products, $_products->getName(), 'name') ?></span>
			</div>
			<div class="short-description">
			    <?php #echo $_products->getDealsDesc(); ?>
			</div>
			<div class="price-section price-box">
			    <div class="price-box">
    				<p class="old-price">
        				<span class="price-label">Regular Price:</span>
        				<span class="price" id="old-price-<?php #echo $_products->getId(); ?>"><?php #echo Mage::helper('core')->currency($_products->getPrice());?></span>
    				</p>
    				<p class="special-price">
        				<span class="price-label">Special Price</span>
            			<span class="price" id="product-price-<?php #echo $_products->getId(); ?>"><?php #echo Mage::helper('core')->currency($_products->getFinalPrice());?></span>
    				</p>
				</div>
			    <?php //echo $this->getPriceHtml($_products, true) ?> // do not needed
			</div>
			<div class="grab-btn">
			    <a href="<?php #echo $product_list_block->getAddToCartUrl($_products); ?>">Grab It!</a>
			</div>
		    </div>
		    <?php //$discount_percent = $customblocks_index->getDiscountPercentage($_product->getId()); ?> // do not needed
		    <?php #if($discount_percent > 0): ?>
		    	<div class="tag"><p><?php #echo $discount_percent; ?>% <span>Off</span></p></div>
		    <?php #endif; ?>
		</li>
	    <?php #endforeach; ?>
        </ul>
    </div>
</div>-->
<?php #endif; ?>
<div class="deal-para">
	<h3>
    	<span>Great Deals. Handpicked For You</span>
    </h3>
    <p>Handpicked deals from across categories with assured savings for you. If you like the deal, make sure to grab it quickly before stocks run out. 
</p>
</div>
<?php if($weekly_deal_count): ?>
<div class="deals-section week">
    <div class="deals-heading">
        <h1 class="deal-title">
            <!--div class="deal-icon">Deals</div-->
            <span>Deals of the Week
			<!--img src="<?php #echo $this->getSkinUrl('images/deals-of-the-week.png'); ?>"-->
			</span>
        </h1>
		
        <div class="deal-timer">
			<div class='deals-text'>Deals Ends on</div>
            <div class="timer-section"><?php echo $weeklycountdown; ?></div>                          
        </div>
    </div>
    <div class="deal-list-section">
        <ul class="deal-listingss">
	    <?php foreach($weekly_deals as $_product): ?>
	    	<?php $discount_percent = $customblocks_index->getDealsDiscountPercent($_product->getId()); ?>
		<li class="item">
		    <div class="product-img">
			<a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->getImageLabel($_product, 'small_image') ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(180); ?>" /></a>
		    </div>
		    <div class="product-info-sec">
			<div class="product-name-sec">
			    <a href="<?php echo $_product->getProductUrl(); ?>"><span><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span></a>
			</div>
			<div class="short-description">
			    <?php echo $_product->getDealsDesc(); ?>
			</div>
			<div class="price-section price-box">
				<div class="price-box">
    				<p class="old-price">
        				<span class="price-label">Regular Price:</span>
        				<span class="price" id="old-price-<?php echo $_product->getId(); ?>"><?php echo Mage::helper('core')->currency($_product->getPrice());?></span>
    				</p>
    				<p class="special-price">
        				<span class="price-label">Special Price</span>
            			<span class="price" id="product-price-<?php echo $_product->getId(); ?>"><?php echo Mage::helper('core')->currency($_product->getFinalPrice());?></span>
    				</p>
				</div>
				<?php //echo $this->getPriceHtml($_product, true) ?>
			</div>
			<div class="grab-btn">
			    <a href="<?php echo $product_list_block->getAddToCartUrl($_product); ?>">Grab It!</a>
			</div>
		    </div>
		    <?php if($discount_percent > 0): ?>
		    	<div class="tag"><p><?php echo $discount_percent; ?>% <span>Off</span></p></div>
		    <?php endif; ?>
		</li>
	    <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>

<?php if(!$weekly_deal_count && !$daily_deal_count): ?>
	<p class="note-msg">There are no either daily deals not weekly deals.</p>
<?php endif; ?>

<script type="text/javascript">
jQuery(document).ready(function() {
	var window_width = jQuery(window).width();
	var daily_deal_count = "<?php echo $daily_deal_count; ?>";
	var weekly_deal_count = "<?php echo $weekly_deal_count; ?>";

	/*if(daily_deal_count > 3){
		jQuery('.deal-listing').bxSlider({
	        slideWidth: 220,
	        minSlides: 2,
	        maxSlides: 3,
	        moveSlides: 1,
	        slideMargin: 11,
	        auto: false,
	        pager: false,
	        controls:true,
	    });
	}else if((window_width <= 980 && window_width >= 768) && daily_deal_count > 2){
	    jQuery('.deal-listing').bxSlider({
	        slideWidth: 220,
	        minSlides: 2,
	        maxSlides: 2,
	        moveSlides: 1,
	        slideMargin: 11,
	        auto: false,
	        pager: false,
	        controls:true,
	    });
	}
    
    if(weekly_deal_count > 3){
    	jQuery('.deal-listingss').bxSlider({
		slideWidth: 220,
	        minSlides: 2,
	        maxSlides: 3,
	        moveSlides: 1,
	        slideMargin: 11,
	        auto: false,
	        pager: false,
	        controls:true,
		});
    }else if((window_width <= 980 && window_width >= 768) && weekly_deal_count > 2){
	jQuery('.deal-listingss').bxSlider({
    		slideWidth: 220,
	        minSlides: 2,
	        maxSlides: 2,
	        moveSlides: 1,
	        slideMargin: 11,
	        auto: false,
	        pager: false,
	        controls:true,
		});
    }*/
});
</script>