<div class="category-products products_homeslider">
        <h2 class="home-slider-heading">Best Sellers</h2>
        <ul class="products-grid products-grid--max-4-col first last odd" id="homeproslider1">
                <li class="item">
                        <a href="#" title="A" class="product-image">
                                <img src="<?php echo $this->getSkinUrl('images/product1.png'); ?>" alt="Home Product1">
                        </a>
                        <div class="product-info">
                                <h2 class="product-name"><a href="#" title="Macbook">Macbook</a></h2>
                <div class="price-box">
                   <span class="regular-price">
                     <span class="price">Rs. 87,000</span>
                   </span>
                </div>
                <div class="info-inner">
                                        <div class="rating">
                                                <ul>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                        </ul>
                        <p>105 Rating</p>
                                        </div>
                                </div>                 
                        </div>
                </li>
                <li class="item">
                        <a href="#" title="A" class="product-image">
                                <img src="<?php echo $this->getSkinUrl('images/product4.jpg'); ?>" alt="Home Product">
                        </a>
                        <div class="product-info">
                                <h2 class="product-name"><a href="#" title="Macbook">Macbook</a></h2>
                                <div class="price-box">
                                        <span class="regular-price">
                                                <span class="price">Rs. 87,000</span>
                                        </span>
                </div>
                <div class="info-inner">
                                        <div class="rating">
                        <ul>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                        </ul>
                        <p>105 Rating</p>
                        </div>
                                </div>                 
                        </div>
                </li>
                <li class="item">
                        <a href="#" title="A" class="product-image">
                                <img src="<?php echo $this->getSkinUrl('images/product3.jpg'); ?>" alt="A">
                        </a>
                        <div class="product-info">
                                <h2 class="product-name"><a href="#" title="Macbook">Macbook</a></h2>
                <div class="price-box">
                                        <span class="regular-price">
                                                <span class="price">Rs. 87,000</span>
                   </span>
                </div>
                <div class="info-inner">
                                        <div class="rating">
                                                <ul>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                        </ul>
                        <p>105 Rating</p>
                        </div>
                                </div>                 
                        </div>
                </li>
                <li class="item">
                        <a href="#" title="A" class="product-image">
                                <img src="<?php echo $this->getSkinUrl('images/product4.jpg'); ?>" alt="A">
                        </a>
                        <div class="product-info">
                                <h2 class="product-name"><a href="#" title="Macbook">Macbook</a></h2>
                <div class="price-box">
                                        <span class="regular-price">
                                                <span class="price">Rs. 87,000</span>
                   </span>
                </div>
                <div class="info-inner">
                                        <div class="rating">
                        <ul>
                                <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                        </ul>
                        <p>105 Rating</p>
                                        </div>
                                </div>                 
                        </div>
                </li>
                <li class="item">
                        <a href="#" title="A" class="product-image">
                                <img src="<?php echo $this->getSkinUrl('images/product4.jpg'); ?>" alt="A">
                        </a>
                        <div class="product-info">
                                <h2 class="product-name"><a href="#" title="Macbook">Macbook</a></h2>
                <div class="price-box">
                                        <span class="regular-price">
                                                <span class="price">Rs. 87,000</span>
                        </span>
                </div>
                <div class="info-inner">
                                        <div class="rating">
                        <ul>
                                <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                        </ul>
                        <p>105 Rating</p>
                                        </div>
                                </div>                 
                        </div>
                </li>
                <li class="item">
                        <a href="#" title="A" class="product-image">
                                <img src="<?php echo $this->getSkinUrl('images/product4.jpg'); ?>" alt="A">
                        </a>
                        <div class="product-info">
                                <h2 class="product-name"><a href="#" title="Macbook">Macbook</a></h2>
                <div class="price-box">
                                        <span class="regular-price">
                                                <span class="price">Rs. 87,000</span>
                                        </span>
                </div>
                <div class="info-inner">
                                        <div class="rating">
                        <ul>
                                <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                        </ul>
                        <p>105 Rating</p>
                        </div>
                                </div>                 
                        </div>
                </li>
                <li class="item last">
                        <div class="clr"></div>
                        <a href="#" title="A" class="product-image">
                                <img src="<?php echo $this->getSkinUrl('images/product3.jpg'); ?>" alt="A">
                        </a>
                        <div class="product-info">
                                <h2 class="product-name"><a href="#" title="Macbook">Macbook</a></h2>
                                <div class="price-box">
                                        <span class="regular-price">
                                                <span class="price">Rs. 87,000</span>
                   </span>
                </div>
                <div class="info-inner">
                                        <div class="rating">
                        <ul>
                                <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                                                        <li><img src="<?php echo $this->getSkinUrl('images/yellow-star.png'); ?>" /></li>
                        </ul>
                        <p>105 Rating</p>
                        </div>
                                </div>                 
                        </div>
                </li>
        </ul>
</div>