<?php
// Retrieve order
$getSession =Mage::getSingleton('core/session')->getMsg();
$getChecksum =Mage::getSingleton('core/session')->getChecksum();
$urlto_submit = Mage::getStoreConfig('payment/billdesk_cc_dc/urlto_submit');

Mage::log($getSession,null,'sessionr.log');
Mage::log($getChecksum,null,'sessionr.log');
?>
<form name='billdeskform' method='POST' action='https://pgi.billdesk.com/pgidsk/PGIMerchantPayment'>
	<input type='hidden' name='msg' value='<?php echo $getSession; ?>' />
</form>
<script type="text/javascript">
document.billdeskform.submit();
</script>