<?php
   //$skinUrl  = $this->getSkinUrl();
   //$basenUrl = $this->getBaseUrl();
   //276361354 
   $id = '';
   $id =  $this->getRequest()->getParam('quikrid');
?>

<div class="gadgetModuleContainer">
     <h1>Introducing Quikr Guaranteed Purchase in partnership with Electronics Bazaar</h1>
    <h2>Sell your product in 60 seconds</h2>
     <ul class="gadgetList">
  
        <li>
             <div class="imgContent">
                <a href="http://www.electronicsbazaar.com/quikr-sell-ur-laptop?quikrid=<?php echo $id ?>"><i class="fa fa-laptop" aria-hidden="true"></i></a>
             </div>
            <!--p>
             <a href="http://www.electronicsbazaar.com/quikr-sell-ur-laptop">Laptops</a> 
            </p-->
        </li>

    </ul> 
</div>         