<?php
$products = $this->getNewItems();
?>
<?php if (sizeof($products) > 0): ?>
    <script type="text/javascript">
        Object.extend(Product.Config.prototype, {
            reloadOptionLabels: function(){},
            changeSelection: function(){},
            reloadPrice: function(){}
        });
    </script>

    <div id="ampromo-overlay" style="display: none;">
        <div id="ampromo-items" class="<?php echo sizeof($products) > 2 ? 'carousel' : ''?>">
            <h4><?php echo $this->__('Free Items')?></h4>

            <a href="javascript:" class="close"></a>

            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/view/options/js.phtml')->toHtml() ?>
            <?php echo $this->getLayout()->createBlock('core/html_calendar')->setTemplate('page/js/calendar.phtml')->toHtml() ?>

            <a href="javascript:" class="ampromo-carousel-control prev" rel="prev">Previous slide</a>
            <div id="ampromo-carousel-wrapper">
                <div id="ampromo-carousel-content">
                    <?php foreach ($products as $product): ?>
                        <div class="slide">
                            <div class="ampromo-item" data-product-id="<?php echo $product->getId()?>" data-product-sku="<?php echo $product->getSku()?>">
                                <form method="POST" action="<?php echo $this->getFormActionUrl()?>" class="ampromo_items_form" id="ampromo_items_form-<?php echo $product->getId()?>">
                                    <input type='hidden' name='referer' value='<?php echo $this->_getReferer()?>' />
                                    <?php if ($product->getVisibility() != Mage_Catalog_Model_Product_Visibility::VISIBILITY_NOT_VISIBLE):?>
                                    <h4><a href="<?php echo $product->getProductUrl()?>"><?php echo $product->getName()?></a></h4>
                                    <?php else: ?>
                                    <h4><?php echo $product->getName()?></h4>
                                    <?php endif?>
                                    <img src="<?php echo $product->getSmallImageUrl(160, 160) ?>" class="ampromo-item-image" />

                                    <div class="ampromo-item-options">
                                        <?php if ($product->getTypeId() == 'configurable')
                                        {
                                            echo $this->getLayout()
                                                ->createBlock('catalog/product_view_type_configurable')
                                                ->setProduct($product)
                                                ->setTemplate('amasty/ampromo/items/configurable.phtml')
                                                ->toHtml()
                                            ;
                                        }
                                        else if ($product->getTypeId() == 'bundle')
                                        {
                                            echo $this->getLayout()
                                                ->createBlock('ampromo/items_bundle')
                                                ->setProduct($product)
                                                ->setTemplate('bundle/catalog/product/view/type/bundle/options.phtml')
                                                ->toHtml()
                                            ;
                                        }
                                        ?>

                                        <?php echo $this->getLayout()
                                            ->createBlock('ampromo/items_options', '', array('product' => $product))
                                            ->toHtml()
                                        ;?>
                                    </div>

                                    <input type="hidden" value="<?php echo $product->getId() ?>" name="product_id" />

                                    <div class="ampromo-item-buttons">
                                        <button type="button" title="<?php echo $this->__('Add to cart')?>" class="button btn-cart add"><span><span><?php echo $this->__('Add to cart')?></span></span></button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
            <a href="javascript:" class="ampromo-carousel-control next" rel="next">Next slide</a>
        </div>
    </div>
<?php endif ?>
