<?php
    if(Mage::getStoreConfig('cancelorder/customer_general/enabled')):
    ?>
    <div class="page-title"><h1><?php echo $this->__('Cancel Your Order ') ?></h1></div>
    <div class="form-list">
        <form name="track_order" id="track_order" action="" method="post" onsubmit="sendAjax('track_order','<?php  echo Mage::getUrl('*/*/cancelorder');?>'); return false;">
        <!--<form name="track_order" method="post" id="track_order" action="<?php echo Mage::getUrl('*/*/view');?>">-->
            <ul class="form-list">
                <li>
                    <label for="order_id" class="required"><em>*</em><?php echo $this->__('Order Id') ?></label>
                    <div class="input-box">
                        <input type="text" name="order_id" id="order_id" value="<?php if(isset($_SESSION['order_no']) && !empty($_SESSION['order_no'])): echo $_SESSION['order_no']; endif; ?>" title="" class="input-text required-entry" />
                    </div>    
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box" >
                        <input type="text" name="email" id="email_address" value="<?php if(isset($_SESSION['email']) && !empty($_SESSION['email'])): echo $_SESSION['email']; endif; ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>    
                </li>
            </ul>
            <div class="buttons-set">
               <button type="submit" class="button" title="<?php echo $this->__('Cancel Order') ?>" name="track" id="track">
                    <span><span><?php echo $this->__('Search Order') ?></span></span>
                </button>
            </div>

        </form>
        <div id="loading-details" class="loading-details" style="display:none">
            <div id="loading-mask" >
                <p class="loader" id="loading_mask_loader"><img width="180px" src="<?php echo $this->getSkinUrl('cancelorder/images/ajax-loader.gif') ?>" alt="<?php echo Mage::helper('adminhtml')->__('Loading...') ?>"/><br/><?php echo $this->__('Please wait...') ?></p>
            </div>
        </div>
    </div>  



    <div id="oderinfo" class="order-info-message"></div>




    <script type="text/javascript">
        var validateForm = new VarienForm('track_order', true);
    </script>           
    <script type="text/javascript">

        function galuuuaaa()
        {
            alert (1111);
        }

        function sendAjax(frmId,url){

            if (!validateForm.validator.validate()) {
                return;
            }
            var data = $(frmId).serialize(this);
            $("loading-details").show();
            
      
        new Ajax.Updater(
                {
                    success:"oderinfo"
                },
                
                url,
                {
                    asynchronous:true,
                    evalScripts:false,
                    onComplete:function(request, json){
                        $("loading-details").hide();
                        return false;
                    }, 
                    onLoading:function(request, json){},
                    parameters:data
                }
            ); 
            return false;
        }

    </script>

    <?php if(isset($_SESSION['order_no']) && !empty($_SESSION['order_no']) && isset($_SESSION['email']) && !empty($_SESSION['email'])): ?>

        <script type="text/javascript">
            //alert(1);
            sendAjax('track_order','<?php echo Mage::getUrl('*/*/cancelorder'); ?>');
        </script>

    <?php endif; ?>

    <?php else: ?>
    <?php
        $url = Mage::getBaseUrl();
        Mage::app()->getFrontController()->getResponse()->setRedirect($url);
    ?>
    <?php endif; ?>
 
<?php

    $_SESSION['order_no'] = null;
    $_SESSION['email'] = null;

?>