<?php

	$data = $this->showservicedatalist();


?>



<div class="service-center-container">
    <h1>Service Center</h1>
    <div class="service-center-search clearfix">
        <div class="search-field"><input type="text" name="" placeholder="Service center" /></div>
        <button class="search-btn"><span>Search</span></button>
    </div>
    <form>
        <div class="service-center-content">
            <table class="service-center-table" cellspacing="0" cellpadding="0">
                <thead>
                    <tr>
                        <th>Sr. No.</th>
                        <th>Type</th>
                        <th>ASP Name</th>
                        <th>Address</th>
                        <th>Contact Person</th>
                        <th>Contact Number</th>
                        <th>Email ID</th>
                        <th>Pin Code</th>
                        <th>City/Town</th>
                        <th>State</th>
                        <th>Region</th>
                    </tr>
                </thead>
                <tbody>
                	<?php  foreach ($data as $key => $value): ?>
	                    <tr>
	                        <td><?php echo $value['id'] ?></td>
	                        <td><?php echo $value['type'] ?></td>
	                        <td><?php echo $value['asp_name'] ?></td>
	                        <td><?php echo $value['address'] ?></td>
	                        <td><?php echo $value['contact_person'] ?></td>
	                        <td><?php echo $value['contact_number'] ?></td>
	                        <td><?php echo $value['mail_id'] ?></td>
	                        <td><?php echo $value['pincode'] ?></td>
	                        <td><?php echo $value['city'] ?></td>
	                        <td><?php echo $value['state'] ?></td>
	                        <td><?php echo $value['region'] ?></td>
	                    </tr>
	                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </form>
</div>

