<?php
   //$skinUrl  = $this->getSkinUrl();
   //$basenUrl = $this->getBaseUrl();
?>
<!--div class="gadgetContainer">
     <h1>Click below to <span class="color">Sell your Gadget!</span></h1>
     <ul>
         <li class="pink">
             <div class="imgContent">
                <a href="<?php //echo $basenUrl.'gadget/index/mobile'; ?>">
                    <img src="<?php //echo $skinUrl.'gadget/images/mobile.png'?>" alt="Mobile" />
                </a>
             </div>
            <p>
                <a href="#">Mobile</a>
            </p>
        </li>
    </ul> 
</div--> 

<div class="gadgetModuleContainer">
     <h1>Click below to <span class="color">Sell your Gadget!</span></h1>
     <ul class="gadgetList">
         <!-- <li>
             <div class="imgContent">
              <a href="http://www.electronicsbazaar.com/gadget/index/mobile"><i class="fa fa-mobile" aria-hidden="true"></i></a>
             </div>
            <p>
             <a href="http://www.electronicsbazaar.com/gadget/index/mobile">Mobiles</a>
            </p>
        </li> -->

        <li>
             <div class="imgContent">
              <a href="http://www.electronicsbazaar.com/sell-ur-laptop"><i class="fa fa-laptop" aria-hidden="true"></i></a>
             </div>
            <p>
             <a href="http://www.electronicsbazaar.com/sell-ur-laptop">Laptops</a>
            </p>
        </li>

    </ul> 
</div>