<?php if(!Mage::helper('customer')->isLoggedin()): ?>

	<?php // $referer = Mage::helper('core')->urlEncode(Mage::helper('core/url')->getCurrentUrl()); ?>
	<?php // Mage::getSingleton('customer/session')->setMyCustomAuthUrl(Mage::helper('core/url')->getCurrentUrl()); ?>
	<?php //Mage::getSingleton('customer/session')->setBeforeAuthUrl(Mage::helper('core/url')->getCurrentUrl()); ?>

	<div class="click-content">

		<ul>

            <li><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superdeals/login-txt-img.png'; ?>" border="0" alt="login" /></li>

			<li class="text1">Great products at unbelievable prices, just a click away!!!</li>

			<li class="text2">Click Here for <a href="<?php echo Mage::getUrl('customer/account/login'); ?>">Login</a>, New user ??? <a href="<?php echo Mage::getUrl('customer/account/login'); ?>">Register Here</a></li>

		</ul>

	</div>

	<!--<p>Please <a href="<?php //echo Mage::getUrl('customer/account/login'); ?>">Login</a> to view the page.</p>-->

<?php else: ?>

	<?php $_helper = $this->helper('catalog/output'); ?>

	<?php $product_list_block = new Mage_Catalog_Block_Product_List(); ?>

	<?php $collection = Mage::getModel('catalog/product')->getCollection()->addAttributeToSelect('*')->addFieldToFilter('is_superdeal',1); ?>
	<div class="superdeal-para">

		<div class="superdeals-container">

			<h2><span class="superdeal-yellow">Super</span><span class="superdeal-white">Deals</span></h2>

			<h3><span>Handpicked For You</span></h3>

		    <p>Handpicked deals from across categories with assured savings for you. If you like the deal, make sure to grab it quickly before stocks run out.</p>

	    </div>

	</div>

	<?php //if($weekly_deal_count): ?>

		<div class="superdeals-section week">

		    <div class="superdeals-heading">

		        <h1 class="superdeal-title"><span>Super Deals</span></h1>

		    </div>

		    <div class="superdeal-list-section">

		        <ul class="superdeal-listingss">

			    	<?php foreach($collection as $_product): ?>

			    		<?php //$discount_percent = $customblocks_index->getDealsDiscountPercent($_product->getId()); ?>

						<li class="item">

						    <div class="product-img">

								<a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->getImageLabel($_product, 'small_image') ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(180); ?>" /></a>

						    </div>

				    		<div class="product-info-sec">

								<div class="product-name-sec">

								    <span><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>

								</div>

								<div class="short-description">

								    <?php echo $_product->getDealsDesc(); ?>

								</div>

								<div class="price-section price-box">

									<div class="price-box">

					    				<p class="old-price">

					        				<span class="price-label">Regular Price:</span>

					        				<span class="price" id="old-price-<?php echo $_product->getId(); ?>"><?php echo Mage::helper('core')->currency($_product->getPrice());?></span>

					    				</p>

					    				<p class="special-price">

					        				<span class="price-label">Special Price</span>

					            			<span class="price" id="product-price-<?php echo $_product->getId(); ?>"><?php echo Mage::helper('core')->currency($_product->getFinalPrice());?></span>

					    				</p>

									</div>

									<?php //echo $this->getPriceHtml($_product, true) ?>

								</div>

								<div class="grab-btn">

								    <a href="<?php echo $product_list_block->getAddToCartUrl($_product); ?>">Grab It!</a>

								</div>

				    		</div>

						    <?php if($discount_percent > 0): ?>

						    	<div class="tag"><p><?php echo $discount_percent; ?>% <span>Off</span></p></div>

						    <?php endif; ?>

						</li>

			    	<?php endforeach; ?>

		        </ul>

		    </div>

		</div>

	<?php //endif; ?>



	<?php //if(!$weekly_deal_count && !$daily_deal_count): ?>

		<!--<p class="note-msg">There are no either daily deals not weekly deals.</p> -->

	<?php //endif; ?>

<?php endif; ?> 