<!-- Top Brands Container -->
<div class="top-brands">
<div class="main">
 <div class="brands-heading">
    <h2>Top Brands</h2>
</div>
    <div class="top-brands-container">
        <div class="top-brnads-slider">
        <ul id="" class="brands-slider clearfix">
            <li><a href="https://www.electronicsbazaar.com/catalogsearch/result/?q=HP"><span><img alt="https://www.electronicsbazaar.com/catalogsearch/result/?q=HP" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/hp.png"></span></a></li>
            <li><a href="https://www.electronicsbazaar.com/catalogsearch/result/?q=HTC"><span><img alt="https://www.electronicsbazaar.com/catalogsearch/result/?q=HTC" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/htc.png"></span></a></li>
            <li><a href="https://www.electronicsbazaar.com/catalogsearch/result/?q=Lenovo"><span><img alt="https://www.electronicsbazaar.com/catalogsearch/result/?q=Lenovo" src="https://electronicsbazaar-nquepiv.stackpathdns.com/media/wysiwyg/sell_gadget/mobile/lenovo_brand.png"></span></a></li>
            <?php /*?><li><a href="https://www.electronicsbazaar.com/catalogsearch/result/?q=Nokia"><span><img alt="https://www.electronicsbazaar.com/catalogsearch/result/?q=Nokia" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/nokia.png"></span></a></li>
            <li><a href="https://www.electronicsbazaar.com/catalogsearch/result/?q=BlackBerry"><span><img alt="https://www.electronicsbazaar.com/catalogsearch/result/?q=BlackBerry" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/blackberry.png"></span></a></li> 
            <li><a href="https://www.electronicsbazaar.com/catalogsearch/result/?q=Toshiba"><span><img alt="https://www.electronicsbazaar.com/catalogsearch/result/?q=Toshiba" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/toshiba.png"></span></a></li>
            <?php */ ?>
            <li><a href="https://www.electronicsbazaar.com/catalogsearch/result/?q=Samsung"><span><img alt="samsung" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/samsung.png"></span></a></li> 
            <li><a href="https://www.electronicsbazaar.com/catalogsearch/result/?q=Apple"><span><img alt="apple" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/apple.png"></span></a></li> 
            <li><a href="https://www.electronicsbazaar.com/catalogsearch/result/?q=asus"><span><img alt="https://www.electronicsbazaar.com/catalogsearch/result/?q=asus" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/asus.png"></span></a></li> 
            <li><a href="https://www.electronicsbazaar.com/catalogsearch/result/?q=Dell"><span><img alt="https://www.electronicsbazaar.com/catalogsearch/result/?q=Dell" src="https://www.electronicsbazaar.com/media/wysiwyg/brand_thumbnail/dell.png"></span></a></li>                                                       
            </ul>
        <ul id="top-brands-slider2"></ul>
        </div>
    </div>
    </div>
</div>      

<script type="text/javascript">
	var jq = jQuery.noConflict();
	jq(document).ready(function(){ 
	  jq('.brands-slider').bxSlider({
	     slideWidth: 162,
         auto:true,
		 autoStart: true,
		 speed: 9000, 
		 pager: false,
		 controls: false,
		 pause: false, 
         maxSlides: 7,
         slideMargin:0, 
         infiniteLoop: true 
	  });
	}); 
</script>
