<?php $skin_url =  $this->getSkinUrl(); ?>
<div class="guidelines-container">
    <div class="main">
        <ul class="clearfix">
            <li><a href="<?php echo $this->getUrl('pre-owned-products'); ?>" title="Pre Owned Guidelines"><img src="<?php echo $skin_url;?>images/ebt/pre-owned-products-guidelines.jpg" alt="Pre Owned GuideLines"></a></li>
            <li><a href="<?php echo $this->getUrl('pre-owned-mobile'); ?>" title="Pre Owned Mobile Guidelines"><img src="<?php echo $skin_url;?>images/ebt/pre-owned-mobile-guidelines.jpg" alt="Pre Owned Mobile Guidelines"></a></li>
            <li><a href="<?php echo $this->getUrl('pre-owned-laptop'); ?>" title="Pre Owned Laptop Guidelines"><img src="<?php echo $skin_url;?>images/ebt/pre-owned-laptop-guidelines.jpg" alt="Pre Owned Laptop Guidelines"></a></li>
        </ul>
    </div>
</div>