<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_order_no" class="required"><em>*</em><?php echo $this->__('Your Past Order No For Replacement Against this current Order#') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('Order No#') ?>" class="input-text required-entry" id="<?php echo $_code ?>_order_no" name="payment[order_no]" value="<?php echo $this->htmlEscape($this->getInfoData('order_no')) ?>" />
        </span>
    </li>
    <div>
    	<?php echo $this->getMethod()->getConfigData('message');?>
    	<br />
	</div>
</ul>