<?php $_productCollection = Mage::helper('catalog/product_compare')->getItemCollection(); ?>
<?php //$_helper = $this->helper('catalog/product_compare'); ?>
<?php $productCollectionCompare = $_productCollection->getData(); ?>
<?php $_helper = Mage::helper('catalog/product_compare'); ?>
<?php //$compare_block = Mage::helper('catalog/product_compare')->getItemCollection(); ?>
<?php $compare_block = new Mage_Catalog_Helper_Product_Compare(); ?>
<div class="ajaxcompare">
<?php if(count($productCollectionCompare) > 0): ?>
      <div class="compare-section">
            <ul>
                  <?php foreach ($productCollectionCompare as $product): ?>
                        <li>
                              <div class="compare-img">
                                    <?php $pro = Mage::getModel('catalog/product')->load($product['entity_id']); ?>
                                    <a href="<?php echo Mage::getBaseUrl().$pro->getRequestPath(); ?>"><img src="<?php echo Mage::helper('catalog/image')->init($pro, 'small_image')->resize(50,50); ?>" alt="<?php echo $pro->getName() ?>" /></a>
                              </div>
                              <div class="compare-product-name">
                                    <p><a href="<?php echo Mage::getBaseUrl().$pro->getRequestPath(); ?>"><?php echo $pro->getName(); ?></a></p>
                              </div>
                              <a href="<?php echo Mage::getUrl('catalog/product_compare/remove/').'product/'.$product['entity_id']; ?>" class="remove-product">Remove</a>
                        </li>
                  <?php endforeach; ?>
                  <li>
                        <div class="btn-section">
                              <!--<a href="#" class="remove-frame">Remove</a>-->
                              <!--<button type="button" title="<?php //echo $this->__('Compare') ?>" class="button" onclick="popWin('<?php //echo $_helper->getListUrl() ?>','compare','top:0,left:0,width=8620,height=600,resizable=yes,scrollbars=yes')"><span><span><?php //echo $this->__('Compare') ?></span></span></button>-->
                              <?php $compare_index = $this->getUrl('catalog/product_compare/index/'); ?>
                              <button type="button" title="<?php echo $this->__('Compare') ?>" class="button" onclick="window.open('<?php echo $compare_index; ?>','_blank');"><span><span><?php echo $this->__('Compare') ?></span></span></button>
                              <!--<button class="button" title="Compare" type="button"><span><span>Compare</span></span></button>-->
                        </div>
                  </li>
            </ul>
      </div>
<?php endif; ?>
</div>