<div class="vow-delight-program-container">

	<div class="vow-delight-program-banner">        
	  <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/rwd/revamp/images/new-images/vow-delight/vow-delight-landing-banner.jpg">
    </div>
    
    <div class="vow-delight-program-content">
    	<p>INTRODUCING 100% HASSLE FREE REPLACEMENT PROGRAM, IN JUST 3 CLICKS</p>

    	 <ul class="vow-delight-program-steps-list">
    		<li class="vow-delight-step1">CLICK ON VOW CUSTOMER DELIGHT ICON ON OUR WEBSITE</li>
    		<li class="vow-delight-step2">ENTER THE lMEI NUMBER AND SUBMIT</li>
    		<li class="vow-delight-step3">GET THE FREE REPLACEMENT UNIT AND DEFECTIVE UNITS PICKED UP</li>
    	</ul>

    	<p>FOR MORE INFORMATIONS TALK TO YOUR AREA RELATIONSHIP MANAGER</p>

    	<span class="vow-delight-btn"><a href="<?php echo Mage::getBaseUrl(); ?>vowdelight"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/rwd/revamp/images/new-images/vow-delight-button.png" alt="Vow Delight"></a></span>
    </div>

</div>
