<div class="new-gadget-popup-container popup-vow">
      <div class="new-gadget-popup-inner-content">
      	<span class="new-gadget-close-popup">X</span>
      	<h1>How  to find IMEI Number ?</h1>
      	<ul>
      		<li>
      			<h2>How to find Imei Number on Android ?</h2>
      			<p>Open the Android Settings menu>Tap "About Phone"> Tap "Status"<br>
      				OR<br>
      				Open the dialer on your phone and type *#06# using the keypad
      			</p>
      		</li>
      		<li>
      			<h2>How to find Imei Number on iPhone ?</h2>
      			<p>Open the Apple Settings on the phone > Tap “General” > Tap “About”<br>
      				OR<br>
      			Open the dialer on your phone and type *#06# using the keypad</p>
      		</li>
      	</ul>
      	<div class="gadget-icon"><img src="<?php echo $this->getSkinUrl(); ?>images/ebt/gadget-mobile-icon.png"></div>
      </div>
</div>