<?php $session = Mage::getSingleton('core/session'); ?>
<div class="inner-main-container blue-btm-border">
  <div class="vow-delight-success">

    <div class="page-title">
        <h1 class="success-head">SUCCESS!</h1>
    </div>
    
    <p>Your request has been successfully submitted.</p>

    <div class="para-s">
        <p>Your New Order no. is: <a href="#"><span><?php echo $session->getData('new_order_no'); ?></span></a>.</p>
    </div>
    
    <p>Your replacement device/s will be delivered within 3-5 working days.</p>

    <div class="buttons-set">
        <button type="button" class="button btn-address" title="Track Your Order" onclick="window.location='<?php echo Mage::getBaseUrl(); ?>track/order'"><span><span>Track Your Order</span></span></button>    
        <button type="button" class="button btn-address" title="Continue Shopping" onclick="window.location='<?php echo Mage::getBaseUrl(); ?>'"><span><span>Continue Shopping</span></span></button>
    </div>

  </div>
</div>
<?php Mage::getSingleton('core/session')->unsNewOrderNo(); ?>
<?php Mage::getSingleton('core/session')->unsNewAwbNo(); ?>
<?php Mage::getSingleton('core/session')->unsImeiList(); ?>