<div class="inner-main-container blue-btm-border">
  <div class="vow-delight-success">

    <div class="page-title">
        <h1 class="success-head">SUCCESS!</h1>
    </div>
    
    <p>Your order replace request recieved and processed!   </p>

    <div class="para-s">
        <p>Your New Order # is: <a href="#"><span>200078673</span></a>.</p>
    </div>
    
    <p>AWB # is: <a href="#"><span>020 5555 5555</span></a>.</p>

    <div class="buttons-set">
        <button type="button" class="button btn-address" title="" onclick=""><span><span>Track your Order</span></span></button>    
        <button type="button" class="button btn-address" title=""><span><span>Continue Shopping</span></span></button>
    </div>

  </div>
</div>