<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td style="width:50%;"><h3 class="icon-head head-adminhtml-index">Manage Bluedart Pincodes</h3></td>
            
        </tr>
    </tbody></table>
</div>
<div>
	<form action='<?php echo Mage::helper("adminhtml")->getUrl("admin_operations/adminhtml_bluedartpincodes/updateBluedartPincodes");?>' name="uploadFile" id="uploadFile" method="post" enctype="multipart/form-data">
	<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>">
	<table cellspacing="0" style="width: 100%">
		<tr>
			<td><span>Upload File : </span></td>
		    <td>
				<!-- <textarea name="increment_ids" id="increment_ids" style="width:50%;height:100px" class="required-entry input-text"></textarea> -->
				<input type="file" name="file" id="file" accept=".csv" style="width:100%;">
				<span style="float: left;width: 50%;">Upload file in .csv format only.</span>
			</td>
		</tr>
		<tr>
			<td align="right" colspan="2"><button id="id_8900456144c3f02698f60a534df78c68" title="Search" type="submit" class="scalable task"style=""><span><span><span>Submit</span></span></span></button></td>
		</tr>
	
	</table>
	</form>
</div>
<script type="text/javascript">
    //< ![CDATA[
        var cancelOrder = new VarienForm('cancelOrder', true);
    //]]>
</script>