<div class="popup-container">
  <div id="loginregister" class="login-register-container">
    <span class="close-button"><a>X</a></span>
    <ul class="login-register-tabs clearfix">
      <li><a href="#tabs-1">Partner Login</a></li>
      <li><a href="#tabs-2">Create New Account</a></li>
    </ul>
    <div id="tabs-1" class="login-container">
      <div class="login-content">
        <ul>
          <li>
            <label>Email</label>
            <div class="input-field"><input type="text" name=""></div>
          </li>
          <li>
            <label>Passowrd</label>
            <div class="input-field"><input type="password" name=""></div>
          </li>
          <li>
            <label>Business Type</label>
            <div class="input-field clearfix">
              <div class="select">
                <input id="option1" type="radio" name="retailer" value="retailer">
                  <label for="option1">Laptop Retailer</label>
              </div>
              <div class="select">
                <input id="option2" type="radio" name="retailer" value="retailer">
                  <label for="option2">Mobile Retailer</label>
              </div>
              <div class="select">
                <input id="option3" type="radio" name="retailer" value="retailer">
                  <label for="option3">Both</label>
              </div>
            </div>
          </li>
        </ul>
        <div class="button-container">
          <button class="button"><span><span>Login</span></span></button>
        </div>
        <div class="clearfix">
          <!-- <div class="remember-me"><input type="checkbox" name=""> Remember me</div> -->
          <div id="remember-me-box" class="remember-me control clearfix">
                <div class="input-box">
                  <input type="checkbox" class="checkbox" id="remember_me" title="Remember Me">
              </div>
              <label for="remember_me">Remember Me</label>
          </div>
          <div class="forgot-password"><a href="#">Forgot Password?</a></div>
        </div>
      </div>
      <div class="login-register-image">
        <img src="http://180.149.246.49/electronicsbazaar/skin/frontend/rwd/ebtronics/images/ebt/login-image.png" />
      </div>
    </div>

    <div id="tabs-2" class="register-container">
      <div class="register-content">
        <ul class="clearfix">
          <li>
            <label>Partner Store Name</label>
            <div class="input-field"><input type="text" name=""></div>
          </li>
          <li>
            <label>Mobile</label>
            <div class="input-field"><input type="text" name=""></div>
          </li>
          <li>
            <label>Email</label>
            <div class="input-field"><input type="text" name=""></div>
          </li>
          <li>
            <label>City</label>
            <div class="input-field"><input type="text" name=""></div>
          </li>
          <li>
            <label>Referred By</label>
            <div class="input-field"><input type="text" name=""></div>
          </li>
          <li>
            <label>Password</label>
            <div class="input-field"><input type="password" name=""></div>
          </li>
          <li>
            <label>Confirm Password</label>
            <div class="input-field"><input type="password" name=""></div>
          </li>
          <li>
            <label>EB Pin</label>
            <div class="input-field"><input type="text" name=""></div>
          </li>
          <li class="business-type">
            <label>Business Type</label>
            <div class="input-field clearfix">
              <div class="select">
                <input id="option4" type="radio" name="register-retailer" value="register-retailer">
                  <label for="option4">Laptop Retailer</label>
              </div>
              <div class="select">
                <input id="option5" type="radio" name="register-retailer" value="register-retailer">
                  <label for="option5">Mobile Retailer</label>
              </div>
              <div class="select">
                <input id="option6" type="radio" name="register-retailer" value="register-retailer">
                  <label for="option6">Both</label>
              </div>
            </div>
          </li>
        </ul>
        <div class="button-container">
          <button class="button eb-pin-button"><span><span>Click here to Generate EB Pin<span class="break-line"> for Mobile Verification</span></span></span></button>
          <button class="button"><span><span>Register</span></span></button>
        </div>
      </div>
      <div class="login-register-image">
        <img src="http://180.149.246.49/electronicsbazaar/skin/frontend/rwd/ebtronics/images/ebt/register-image.png" />
      </div>
    </div>
    
  </div>
</div>