<?php
/**
 * 
 *
 * @category Sunarc
 * @package Splitorder-magento
 * @author Sunarc Team <info@sunarctechnologies.com>
 * @copyright Sunarc (http://sunarctechnologies.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Your order has been received.') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!!') ?></h2>

<?php $orderIds= Mage::getSingleton('core/session')->getOrderIds(); ?>
<?php //print_r($orderIds); ?>
<p data-role="order-numbers">
    <?php $flag = false ?>
    <?php echo $this->__('Your order number is ') ?>
    <?php foreach ($orderIds as $orderId=>$incrementId):
        //echo "$orderId -> $incrementId";
        ?>
        <?php if ($flag): ?>
        <?php echo ', ' ?>
    <?php endif; ?>
        <?php $flag = true ?>
        <a href="<?php echo Mage::getUrl('sales/order/view', array('order_id'=>$orderId));   ?>"><?php echo $incrementId; ?></a>
        <?php //echo Mage::getUrl('*/sales/order/view', array('order_id'=>$orderId)); ?>
    <?php endforeach; ?>
</p>

<div class="buttons-set">
    <button type="button" class="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue Shopping')) ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>
