<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost', array('_secure' => $this->getRequest()->isSecure())) ?>" method="post" id="form-validate-email" style="display:none">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>    
       
        <p class="restore-account"><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <ul class="form-list">
            <li>
                <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                <div class="input-box">
                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                </div>
            </li>
        </ul>
       
       <div id="forgotpassword-button-set" class="forgotpassword-button">		        	
       <input type ="submit" value="Submit" name="submit">
      <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
	</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm2 = new VarienForm('form-validate-email', true);
//]]>
</script>
